MC-40589: Document page builder preview limitation for filtering/sorting configurable, grouped and bundle products by price.
magento/merchdocs pull request #1016
Opened 2021-01-28 20:44 UTC by bubasuma

## Purpose of this pull request

This pull request (PR) adds a warning information about page builder preview limitation for filtering/sorting configurable, grouped and bundle products by price.

## Magento release version

- [x] 2.4.x

- [x] 2.3.x

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [x] Other feature set, please specify: Page Builder extension

## Affected documentation pages

- https://docs.magento.com/user-guide/cms/page-builder-add-content-products.html

2021-02-01 14:16 UTC, dobooth requested changes

2021-02-01 14:16 UTC, dobooth commented on src/cms/page-builder-add-content-products.md
> +   Configurable, grouped and bundle (dynamic price) products price is undefined in admin area. Therefore, such products will not be displayed in the **preview** if the products are filtered by price.
```suggestion
   Prices for configurable, grouped and bundled (dynamic price) products are undefined in the Admin area. Therefore, these products are not displayed in the **preview** if the products are filtered by price. These products cannot be ordered correctly in the **preview** if ordered by price.
```

2021-02-08 13:48 UTC, dobooth commented
Please set this so we can update this PR: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

2021-02-08 14:13 UTC, bubasuma commented
Hi @dobooth, I think in order for it to work you need write access to our L3 organization merchdocs fork, I can’t grant it, but you can request it in #github-permissions Slack channel.

2021-02-09 16:31 UTC, dobooth approved these changes

2021-02-09 16:33 UTC, dobooth commented
running tests

2021-02-09 16:44 UTC, merged