MC-40719: Product Thumbnails not switching properly for Config product
magento/merchdocs pull request #1038
Opened 2021-02-05 21:34 UTC by thiaramus

## Purpose of this pull request

This pull request (PR) is to clarify the default behavior of the Image Gallery for configurable products when a user switches between product configurations. To add a note that this behavior can be controlled with the swatch attribute settings, and by the theme.

Over the years we had many opened support tickets due to the misunderstanding of the default behavior since it wasn't described anywhere. 

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [x] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/catalog/product-create-configurable.html
- https://docs.magento.com/user-guide/catalog/swatches.html
- https://docs.magento.com/user-guide/catalog/swatch-create.html

## Links to Magento source code or PRs

- https://jira.corp.magento.com/browse/MC-40719

2021-02-08 13:43 UTC, dobooth requested changes

2021-02-08 13:43 UTC, dobooth commented on src/catalog/product-create-configurable.md
> +- It is controlled by the theme how Image Gallery will behave when a user switches between product configurations. Default behavior for Blank theme is to override the parent configurable product imag
```suggestion
- The theme controls how the Image Gallery behaves when a user switches between product configurations. The default behavior for the Blank theme is to override the parent configurable product images with the selected product variation. For the Luma theme, the default behavior is to prepend the selected product variation images to the parent configurable product images.
```

2021-02-08 13:43 UTC, dobooth commented on src/catalog/swatch-create.md
> +1. If it is preferred to not display corresponding simple product images when the swatch is selected on the product display page, set the "Update Product Preview Image" option value to "No".
```suggestion
1. If you prefer to not display corresponding simple product images when the swatch is selected on the product display page, set the "Update Product Preview Image" option value to "No".
```

2021-02-08 13:43 UTC, dobooth commented on src/catalog/swatch-create.md
> +1. If it is preferred to not display corresponding simple product images when the swatch is selected on the product display page, set the "Update Product Preview Image" option value to "No".
```suggestion
1. If you prefer to not display corresponding simple product images when the swatch is selected on the product display page, set the "Update Product Preview Image" option value to "No".
```

2021-02-08 13:43 UTC, dobooth commented on src/catalog/swatches.md
> +Swatch attributes can be configured to not display corresponding simple product images when the swatch is selected by setting the "Update Product Preview Image" option value to "No" at the attribute
```suggestion
Swatch attributes can be configured to not display corresponding simple product images when the swatch is selected by setting the "Update Product Preview Image" option value to "No" on the Attribute Edit page in the Admin.
```

2021-02-08 17:52 UTC, odubovyk approved these changes

2021-02-09 17:34 UTC, dobooth approved these changes

2021-02-09 17:45 UTC, dobooth commented
running tests

2021-02-09 17:51 UTC, merged