magento/merchdocs#: adds items to the table in storefront settings for catalog section
magento/merchdocs pull request #1075
Opened 2021-03-03 10:31 UTC by volodymyrDashuk

## Purpose of this pull request

This pull request (PR) adds items to the table in Storefront settings for Catalog section to the existing documentation.

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [x] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/configuration/catalog/catalog.html

2021-03-04 19:51 UTC, leslietilling requested changes
Just some minor editorial changes needed.

2021-03-04 19:51 UTC, leslietilling commented on src/configuration/catalog/catalog.md
> +|Show Swatches in Product List|Store View|Determines if the swatches in Product List appears. Options: Yes / No|
```suggestion
|Show Swatches in Product List|Store View|Determines if the swatches appear in the Product List. Options: Yes / No|
```

2021-03-04 19:51 UTC, leslietilling commented on src/configuration/catalog/catalog.md
> +|Show Swatch Tooltip|Store View|Determines if the swatch Tooltip appears. Options: Yes / No|
```suggestion
|Show Swatch Tooltip|Store View|Determines if the swatch tooltip appears. Options: Yes / No|
```

2021-03-05 07:43 UTC, volodymyrDashuk commented
Hi @leslietilling 
All your suggestions have been implemented!
Could you please verify this PR?
Thank you!

2021-03-05 07:44 UTC, volodymyrDashuk commented on src/configuration/catalog/catalog.md
> +|Show Swatches in Product List|Store View|Determines if the swatches in Product List appears. Options: Yes / No|
done!

2021-03-05 07:44 UTC, volodymyrDashuk commented on src/configuration/catalog/catalog.md
> +|Show Swatch Tooltip|Store View|Determines if the swatch Tooltip appears. Options: Yes / No|
done!

2021-03-05 21:22 UTC, leslietilling approved these changes

2021-03-05 21:27 UTC, leslietilling commented
running tests

2021-03-05 21:35 UTC, merged