magento/merchdocs#1103: Allow Reorders from customer account
magento/merchdocs pull request #1105
Opened 2021-03-24 14:46 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

Fix pull request fixes https://github.com/magento/merchdocs/issues/1103

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x ] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

-  https://docs.magento.com/user-guide/sales/reorders-allow.html

2021-03-24 14:48 UTC, dobooth commented
Hi @EvheniiaKolkhiieva. Thanks for your contribution! Can you please sign the Adobe CLA so that we may process this PR?

2021-03-24 14:56 UTC, atwixfirster requested changes

2021-03-24 14:56 UTC, atwixfirster commented on src/sales/reorders-allow.md
> +![]({% link images/images/my-orders-view-page1.png %}){: .zoom}
@EvheniiaKolkhiieva , please remove a space at the end of sentence.

Thank you!

2021-03-24 14:56 UTC, atwixfirster commented on src/sales/reorders-allow.md
> +![]({% link images/images/order-view-page.png %}){: .zoom}
The same here.

2021-03-24 14:56 UTC, atwixfirster commented on src/sales/reorders-allow.md
> +## Cart isn’t empty
The same here.

2021-03-24 14:56 UTC, atwixfirster commented on src/sales/reorders-allow.md
> +In case if Cart is not empty and user will click on 'Reorder' button (from “My Orders”  or “Order View” pages), the existing products will be added to the Shopping cart with the recorder products
The same here.

2021-03-24 14:56 UTC, atwixfirster commented on src/sales/reorders-allow.md
> +![]({% link images/images/shopping-cart-view1.png %}){: .zoom}
The same here. After `{: .zoom}`

2021-03-24 14:56 UTC, atwixfirster commented on src/sales/reorders-allow.md
> +1. Open the Orders grid
The same here.

2021-03-24 14:56 UTC, atwixfirster commented on src/sales/reorders-allow.md
> +![]({% link images/images/order-view-admin.png %}){: .zoom}
The same here. After `{: .zoom}`

2021-03-24 14:56 UTC, atwixfirster commented on src/sales/reorders-allow.md
> +2. Click the 'View' button
Please use `1`:

```
1. Click the 'View' button
```

2021-03-24 15:38 UTC, atwixfirster approved these changes
Thank you for your contributions, @EvheniiaKolkhiieva !

Approve from my side ✅

2021-04-02 08:07 UTC, atwixfirster commented
@dobooth , could you please add the next labels to this PR:

- `partners-contribution`
- `Partner: Atwix`

Thank you!

2021-04-05 17:17 UTC, leslietilling reviewed
Edits for grammar, style, and formatting

2021-04-05 17:17 UTC, leslietilling commented on src/sales/reorders-allow.md
> +1. Click the 'View' button
```suggestion
1. Click **View**.
```

2021-04-05 17:17 UTC, leslietilling commented on src/sales/reorders-allow.md
> +“Reorder“ button is displayed on top menu.
```suggestion
   _Reorder_ is displayed in the top button bar.
```

2021-04-05 17:17 UTC, leslietilling commented on src/sales/reorders-allow.md
> +After clicking the "Reorder" button the "Create New Order"page with reorder products will open.
```suggestion
   After you click **Reorder**, the _Create New Order_ page opens with reorder products.
```

2021-04-05 17:17 UTC, leslietilling commented on src/sales/reorders-allow.md
> +![]({% link images/images/order-view-admin.png %}){: .zoom}
```suggestion
   ![]({% link images/images/order-view-admin.png %}){: .zoom}
```

2021-04-05 17:17 UTC, leslietilling commented on src/sales/reorders-allow.md
> +![]({% link images/images/create-reorder-page.png %}){: .zoom}
```suggestion
   ![]({% link images/images/create-reorder-page.png %}){: .zoom}
```

2021-04-05 17:17 UTC, leslietilling commented on src/sales/reorders-allow.md
> +Customer may initiate the reorder functionality for a particular order from the
```suggestion
A customer can initiate the reorder functionality for a specific order from two pages:
```

2021-04-07 09:09 UTC, EvheniiaKolkhiieva commented
Hi, @leslietilling,
Thank you for your reviewing!

I made some changes to the request, could you please check?

Thank you!

2021-04-08 18:36 UTC, leslietilling approved these changes

2021-04-09 15:08 UTC, dobooth commented
@magento import code to magento-devdocs/merchdocs

2021-04-09 15:09 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1105`.

2021-04-09 18:00 UTC, merged