magento/merchdocs#1160 Add a new topic about adding products to the categories
magento/merchdocs pull request #1161
Opened 2021-04-12 11:18 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request adds a new child page for the Products in Category page and describes how to add a new product to a category.

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/catalog/categories-category-products.html

2021-04-19 19:54 UTC, leslietilling requested changes
Some editorial changes and structuring changes for procedures.

2021-04-19 19:54 UTC, leslietilling commented on src/catalog/category-products-add.md
> +For any category, in Magento 2, the Admin can add products that will be displayed in it. The **Products in Category** section lists all the products that are actually assigned to the category. The <s
```suggestion
From the [Products in Category]({% link catalog/categories-category-products.md %}) section , a store administrator can add products to the category. This section lists all the products that are actually assigned to the category and displays <span class="btn">Add Product</span> when **Match products by rule** is set to `No`.
```

2021-04-19 19:54 UTC, leslietilling commented on src/catalog/category-products-add.md
> +1. Click <span class="btn">Add Products</span> and do the following:
```suggestion
1. Click <span class="btn">Add Products</span>.
```

2021-04-19 19:54 UTC, leslietilling commented on src/catalog/category-products-add.md
> +1. Use Search by keyword or filters to find and select the products you need.
```suggestion
1. Use _Search by keyword_ or filters to find the products you want to add.
```

2021-04-19 19:54 UTC, leslietilling commented on src/catalog/category-products-add.md
> +    _Search All Products Tab_
```suggestion
    _Search All Products tab_
```

2021-04-19 19:54 UTC, leslietilling commented on src/catalog/category-products-add.md
> +1. To add a product, set the **Assign option** to **Yes** and click <span class="btn">Save and Close</span>.
```suggestion
1. In the _Assign_ column, toggle the option to **Yes** for each product that you want to add.

   If you want to include all of the displayed products, you can click the menu arrow in the column header and choose **Select All**.

1. To apply your changes, click <span class="btn">Save and Close</span>.
```

2021-04-19 19:54 UTC, leslietilling commented on src/catalog/category-products-add.md
> +|Select All|Marks the checkbox of all records in the list.|
```suggestion
|Select All|Selects the checkbox of all records in the list.|
```

2021-04-19 19:54 UTC, leslietilling commented on src/catalog/category-products-add.md
> +|Select All on This Page|Marks the checkbox of records on the current page.|
```suggestion
|Select All on This Page|Selects the checkbox of records on the current page.|
```

2021-04-19 19:54 UTC, leslietilling commented on src/catalog/category-products-add.md
> +1. Click <span class="btn">Add Products</span> select **Add Products by SKU** tab.
```suggestion
1. Click <span class="btn">Add Products</span>

1. Select the **Add Products by SKU** tab.
```

2021-04-19 19:54 UTC, leslietilling commented on src/catalog/category-products-add.md
> +1. Enter SKUs below, one per line, and click <span class="btn">Assign</span>. To discard the changes, click <span class="btn">Remove</span>.
```suggestion
1. Enter SKUs below, one per line, and click <span class="btn">Assign</span>.

   To discard the changes, click <span class="btn">Remove</span>.
```

2021-04-19 19:54 UTC, leslietilling commented on src/catalog/category-products-add.md
> +1. For approve changes click <span class="btn">Save and Close</span>.
```suggestion
1. To apply your changes, click <span class="btn">Save and Close</span>.
```

2021-04-20 07:50 UTC, ZhovnirMaria commented on src/catalog/category-products-add.md
> +1. For approve changes click <span class="btn">Save and Close</span>.
@leslietilling 
Thank you, done.

2021-04-22 17:53 UTC, leslietilling approved these changes

2021-04-26 16:26 UTC, dobooth commented
@magento import code to magento-devdocs/merchdocs

2021-04-26 16:27 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1161`.

2021-04-29 15:20 UTC, merged