magento/merchdocs#1089: Add RMA how-to instructions to Returns section
magento/merchdocs pull request #1183
Opened 2021-04-14 13:02 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request adds an instruction for how to create returns requests from the Admin side. 

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/sales/returns.html

2021-04-15 11:40 UTC, dobooth requested changes

2021-04-15 11:40 UTC, dobooth commented on src/sales/returns.md
> +    ![]({% link images/images/new-return.png %}){: .zoom}
We can remove this image.

2021-04-15 11:40 UTC, dobooth commented on src/sales/returns.md
> +    ![]({% link images/images/return-item.png %}){: .zoom}
And this one can go as well.

2021-04-15 12:58 UTC, ZhovnirMaria commented on src/sales/returns.md
> +    ![]({% link images/images/return-item.png %}){: .zoom}
@dobooth 
Done, thanks!

2021-04-15 15:15 UTC, leslietilling reviewed
Edits for grammar and style.

2021-04-15 15:15 UTC, leslietilling commented on src/sales/returns.md
> +## Create a Return Request
Sentence case for headings
```suggestion
## Create a return request
```

2021-04-15 15:15 UTC, leslietilling commented on src/sales/returns.md
> +1. To create new return request, go to **Sales** > **Returns** > Click <span class="btn">New Return Request</span>.
```suggestion
1. On the _Admin_ sidebar, go to **Sales** > **Returns**.

1.  Click <span class="btn">New Return Request</span>.
```

2021-04-15 15:15 UTC, leslietilling commented on src/sales/returns.md
> +1. Click on an order with a `Complete` status to create a return request.
```suggestion
1. Click an order with a `Complete` status to create a return request.
```

2021-04-15 15:15 UTC, leslietilling commented on src/sales/returns.md
> +1. Select the **Return Items** tab under the **Return Information** section.
```suggestion
1. Under the _Return Information_ section, select the **Return Items** tab.
```

2021-04-15 15:15 UTC, leslietilling commented on src/sales/returns.md
> +1. Fill in the field **Requested** with the number of items you want to return.
```suggestion
1. For **Requested**, enter the number of items to be returned.
```

2021-04-15 15:15 UTC, leslietilling commented on src/sales/returns.md
> +1. Sets **Return Reason** to one of the following:
```suggestion
1. Set **Return Reason** to one of the following:
```

2021-04-15 15:15 UTC, leslietilling commented on src/sales/returns.md
> +    If the reason for the return is different from those listed in the **Reason for Return** field, you can enter your own in the field that appears below when you select `Other` option.
```suggestion
    If the reason for the return is different from those listed, you can enter your own if you select the `Other` option.
```

2021-04-15 15:15 UTC, leslietilling commented on src/sales/returns.md
> +1. Sets **Item Condition** to one of the following:
```suggestion
1. Set **Item Condition** to one of the following:
```

2021-04-15 15:15 UTC, leslietilling commented on src/sales/returns.md
> +1. Sets **Resolution** to one of the following:
```suggestion
1. Set **Resolution** to one of the following:
```

2021-04-16 08:04 UTC, ZhovnirMaria commented
@leslietilling 
Done, thank you!

2021-04-22 20:29 UTC, leslietilling approved these changes

2021-04-26 13:10 UTC, dobooth approved these changes

2021-04-26 13:10 UTC, dobooth commented
@magento import code to magento-devdocs/merchdocs

2021-04-26 13:11 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1183`.

2021-04-26 15:10 UTC, merged