Duplicate removal about invoice print
magento/merchdocs pull request #1189
Opened 2021-04-15 21:01 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

Since "Printing Invoices" is described in a separate subcategory, it should not be described in the "Creating an Invoice" topic, this only loads the document. This PR removes unnecessary duplicate information
![image](https://user-images.githubusercontent.com/78729171/114937730-d1d18280-9e46-11eb-9db0-6ef0ef583494.png)

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/sales/invoice-create.html

2021-04-15 21:43 UTC, dobooth commented
Any chance you could remove that Acrobat screenshot from what appears to be 1998 from the Printing Invoices topic?

2021-04-15 21:49 UTC, EvheniiaKolkhiieva commented
@dobooth yes, for sure. 

Should I just delete the image in the additional commit or add an updated modern one?

2021-04-20 06:37 UTC, EvheniiaKolkhiieva commented
Hi @dobooth,
I have deleted the Acrobat screenshot from the Printing invoices topic.
Could you please approve?

Thank you!

2021-04-20 13:57 UTC, leslietilling requested changes
Just a few minor edits and this one looks good.

2021-04-20 13:57 UTC, leslietilling commented on src/sales/refunds-customer-account.md
> +|Payment Action |Description
Sentence case for column headings

```suggestion
|Payment action |Description
```

2021-04-20 13:57 UTC, leslietilling commented on src/sales/refunds-customer-account.md
> +|Not Capture |When the invoice is submitted, the system does not capture the payment. It is assumed that you will capture the payment through Magento at a later date. There is a Capture button in the
```suggestion
|Not Capture |When the invoice is submitted, the system does not capture the payment. It is assumed that you will capture the payment through Magento at a later date. There is a _Capture_ button in the completed invoice. Before capturing, you are able to cancel the invoice. After capturing, you are able to create a credit memo and void the invoice.
```

2021-04-20 13:57 UTC, leslietilling commented on src/sales/refunds-customer-account.md
> +Do not select the _Not Capture_ option unless you are certain that you are going to capture the payment through Magento at a later date. You cannot create a credit memo until the payment has been cap
```suggestion
**_Do not_** select the _Not Capture_ option unless you are certain that you are going to capture the payment through Magento at a later date. You cannot create a credit memo until the payment has been captured using the _Capture_ button.
```

2021-04-20 14:26 UTC, EvheniiaKolkhiieva commented
Hi @leslietilling,

I have implemented your edits, could you please approve? 

Thank you!

Re: pay attention, seems the "Adding the "Payment actions block " commit mistakenly got into this PR, since it does not apply to the description above, but I updated the description to combine both edits

2021-04-20 19:30 UTC, EvheniiaKolkhiieva commented on src/sales/refunds-customer-account.md
> +Do not select the _Not Capture_ option unless you are certain that you are going to capture the payment through Magento at a later date. You cannot create a credit memo until the payment has been cap
Done ☑️

2021-04-20 19:30 UTC, EvheniiaKolkhiieva commented on src/sales/refunds-customer-account.md
> +|Not Capture |When the invoice is submitted, the system does not capture the payment. It is assumed that you will capture the payment through Magento at a later date. There is a Capture button in the
Done ☑️

2021-04-20 19:30 UTC, EvheniiaKolkhiieva commented on src/sales/refunds-customer-account.md
> +|Payment Action |Description
Done ☑️

2021-04-29 16:35 UTC, leslietilling approved these changes

2021-04-29 16:48 UTC, leslietilling commented
I will fix the conflict in the team fork.

2021-04-29 16:49 UTC, leslietilling commented
@magento import code to magento-devdocs/merchdocs

2021-04-29 16:51 UTC, magento-engcom-team commented
@leslietilling the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1189`.

2021-04-29 19:11 UTC, EvheniiaKolkhiieva commented
Thank you a lot @leslietilling ☺️

2021-05-05 13:10 UTC, merged