Viewing and using store credit balance on the storefront
magento/merchdocs pull request #1190
Opened 2021-04-15 21:39 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

This pull request (PR) describe viewing and using the store's credit balance in the storefront from the Review & Payments page

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/sales/refunds-customer-account.html

2021-04-16 18:37 UTC, leslietilling requested changes
Edits for grammar and style. Since guide is for merchants/commerce administrators, storefront customer procedures are third person.

2021-04-16 20:41 UTC, EvheniiaKolkhiieva commented
Hi @leslietilling, thank you so much for reviewing.

All your suggestions were implemented, please check!

Thank you!

2021-04-19 18:08 UTC, EvheniiaKolkhiieva commented on src/sales/refunds-customer-account.md
> +1. If you want to cancel the use Store Credit payment click <span class="btn">Remove</span> on the **Order Summary** block.
Done ✅

2021-04-19 18:08 UTC, EvheniiaKolkhiieva commented on src/sales/refunds-customer-account.md
> +1. Pass the **Shipping** step.
Done ✅

2021-04-19 18:08 UTC, EvheniiaKolkhiieva commented on src/sales/refunds-customer-account.md
> +1. Proceed to checkout.
Done ✅

2021-04-19 18:08 UTC, EvheniiaKolkhiieva commented on src/sales/refunds-customer-account.md
> +1. Add product to the cart.
Done ✅

2021-04-19 18:08 UTC, EvheniiaKolkhiieva commented on src/sales/refunds-customer-account.md
> +**Method 2:** From review & payments page
Done ✅

2021-04-19 18:08 UTC, EvheniiaKolkhiieva commented on src/sales/refunds-customer-account.md
> +1. {:.ee-only}You can add the [gift cart]({% link customers/account-dashboard-gift-card.md %}).
Done ✅

2021-04-19 18:08 UTC, EvheniiaKolkhiieva commented on src/sales/refunds-customer-account.md
> +1. From the storefront, log in to account.
Done ✅

2021-04-19 18:08 UTC, EvheniiaKolkhiieva commented on src/sales/refunds-customer-account.md
> +**Method 1:** From customer accoun dashbord
Done ✅

2021-04-21 16:22 UTC, dobooth commented
@magento import code to magento-devdocs/merchdocs

2021-04-21 16:23 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1190`.

2021-04-26 15:10 UTC, merged