Describe the Startup Page block options from Advanced > Admin page
magento/merchdocs pull request #1224
Opened 2021-04-22 11:09 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request:
- describes the Startup Page block options from Advanced > Admin page
- edits the Admin User Emails block

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/configuration/advanced/admin.html?itm_source=merchdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=My%20Account

2021-05-07 19:10 UTC, leslietilling requested changes
A few minor edits

2021-05-07 19:10 UTC, leslietilling commented on src/configuration/advanced/admin.md
> +||[Reviews]({% link reports/review-reports.md %})|By Customer<br />By Products<br />Yotro Reviews|
```suggestion
||[Reviews]({% link reports/review-reports.md %})|By Customer<br />By Products<br />Yotpo Reviews|
```

2021-05-07 19:10 UTC, leslietilling commented on src/configuration/advanced/admin.md
> +||[Business Intelligence]({% link reports/business-intelligence.md %})|Advanced Reporting<br/>BI Essentials<br/>Yotro Analytics|
```suggestion
||[Business Intelligence]({% link reports/business-intelligence.md %})|Advanced Reporting<br/>BI Essentials<br/>Yotpo Analytics|
```

2021-05-07 19:10 UTC, leslietilling commented on src/configuration/advanced/admin.md
> +||Other Settings|[Reward ExchangeRates]({% link marketing/reward-exchange-rates.md %})<br/>[Gift Wrapping]({% link sales/gift-wrap.md %})<br/>[Gift Registry]({% link customers/account-dashboard-gift-
```suggestion
||Other Settings|[Reward Exchange Rates]({% link marketing/reward-exchange-rates.md %})<br/>[Gift Wrapping]({% link sales/gift-wrap.md %})<br/>[Gift Registry]({% link customers/account-dashboard-gift-registry.md %})|
```

2021-05-10 05:45 UTC, ZhovnirMaria commented
@leslietilling 
Thank you! Done ✅

2021-05-11 18:12 UTC, magento-engcom-team commented
@leslietilling the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1224`.

2021-05-14 19:10 UTC, merged