Update the Now Online page, add the Company column and edit customer session lifetime
magento/merchdocs pull request #1226
Opened 2021-04-22 13:38 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request updates the Now Online page, adds the Company column and edits customer session lifetime

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/customers/now-online.html

2021-05-05 14:45 UTC, jcalcaben requested changes

2021-05-05 14:45 UTC, jcalcaben commented on src/customers/now-online.md
> +The **Now Online** option on the Customers menu lists all customers and visitors who are currently online in your store. The interval of time that customers are shown as currently online is set in th
```suggestion
The **Now Online** option on the Customers menu lists all customers and visitors who are currently online in your store. The interval of time that customers are shown as currently online is set in the configuration, and determines how long the customer’s activity is visible from the Admin. By default, the interval is fifteen minutes. The session ends if the keyboard is not used during this time and customers must sign into their accounts again to continue shopping. It is important to note that the contents of the carts are saved for later access.
```

2021-05-06 07:05 UTC, ZhovnirMaria commented on src/customers/now-online.md
> +The **Now Online** option on the Customers menu lists all customers and visitors who are currently online in your store. The interval of time that customers are shown as currently online is set in th
Hi, @jcalcaben , thank you!
Done ✅

2021-05-07 18:39 UTC, jcalcaben commented
@magento import code to magento-devdocs/merchdocs

2021-05-07 18:40 UTC, magento-engcom-team commented
@jcalcaben the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1226`.

2021-05-14 12:50 UTC, merged