Supplement the admin stores configuration list with missing data
magento/merchdocs pull request #1227
Opened 2021-04-22 14:54 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

This pull request (PR) describes:
- Security block
- Yotpo block
- Sales Channels block
-  Dotdigital block
in the admin stores configuration list.
## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/stores/configuration-overview.html

2021-05-05 15:02 UTC, jcalcaben requested changes

2021-05-05 15:02 UTC, jcalcaben commented on src/stores/configuration-overview.md
> +[Dotdigital]({% link configuration/dotdigital.md %}) settings determine the Dotdigital marketing solution setting. Allows set the build segments and triggers, data mapping, and creates a relevant acc
```suggestion
[Dotdigital]({% link configuration/dotdigital.md %}) settings configure the Dotdigital marketing feature. It configures the build segments and triggers, data mapping, and lets you create a relevant account and marketing campaigns.
```

2021-05-07 14:57 UTC, EvheniiaKolkhiieva commented
Hi @jcalcaben, thank you for your review! 
I have implemented all suggestions you describe. Could you please review and approve this PR?

Thank you!

2021-05-07 14:57 UTC, EvheniiaKolkhiieva commented on src/stores/configuration-overview.md
> +[Dotdigital]({% link configuration/dotdigital.md %}) settings determine the Dotdigital marketing solution setting. Allows set the build segments and triggers, data mapping, and creates a relevant acc
Done ✅

2021-05-07 14:57 UTC, EvheniiaKolkhiieva commented on src/stores/configuration-overview.md
> +[Sales Chanel]({% link configuration/sales-channels.md %}) settings determine the clear log history, background tasks source, debag login, and read-only mode setting. Only available when Amazon Sales
Done ✅

2021-05-07 14:57 UTC, EvheniiaKolkhiieva commented on src/stores/configuration-overview.md
> +[Yotpo]({% link configuration/yotpo.md %}) settings determine the Yotpo module, reviews, and visual marketing settings.
Done ✅

2021-05-07 14:57 UTC, EvheniiaKolkhiieva commented on src/stores/configuration-overview.md
> +[Security]({% link configuration/security.md %}) settings determine security settings, 2FA authentication and Google reCapture feature.
Done ✅

2021-05-07 18:40 UTC, jcalcaben approved these changes

2021-05-07 18:41 UTC, magento-engcom-team commented
@jcalcaben the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1227`.

2021-05-07 20:10 UTC, merged