Add fields descriptions for other settings pages
magento/merchdocs pull request #1236
Opened 2021-04-26 14:22 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request adds fields descriptions to the:
- Configurations page
- Product Reviews
- Schedule Design Update

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/catalog/product-scheduled-design-update.html
https://docs.magento.com/user-guide/catalog/settings-advanced-product-reviews.html
https://docs.magento.com/user-guide/catalog/product-configurations.html

2021-04-27 16:50 UTC, dobooth requested changes

2021-04-27 16:50 UTC, dobooth commented on src/catalog/product-configurations.md
> +|Image|Product image.|
Generally, we don't use periods in these table descriptions, unless it is an actual sentence.

2021-04-27 16:51 UTC, dobooth commented
And there is a merge conflict here.

2021-04-28 08:30 UTC, ZhovnirMaria commented
@dobooth Thanks, done ✅ 
Have a good day 😊

2021-05-07 19:29 UTC, leslietilling requested changes
A few minor edits for style consistency

2021-05-07 19:29 UTC, leslietilling commented on src/catalog/settings-advanced-product-reviews.md
> +|Type|Type of user who left the review. Options: **Guest**, **Customer**.|
```suggestion
|Type|Type of user who left the review (Guest or Customer)|
```

2021-05-07 19:29 UTC, leslietilling commented on src/catalog/settings-advanced-product-reviews.md
> +|Status|Review status. Options: **Pending**, **Approved**, **Not Approved**.|
```suggestion
|Status|Review status (Pending, Approved, or Not Approved)|
```

2021-05-07 19:29 UTC, leslietilling commented on src/catalog/settings-advanced-product-reviews.md
>  1. On the _Admin_ sidebar, go to **Catalog** > **Products** > Edit the Product > _Product Reviews_ section.
Let's fix this while we are here

```suggestion
1. On the _Admin_ sidebar, go to **Catalog** > **Products**.

1. Locate the product and open it in edit mode.

1. Scroll to the _Product Reviews_ section.
```

2021-05-10 06:01 UTC, ZhovnirMaria commented
@leslietilling, hi!
Thank you, Done ☑️

2021-05-11 18:08 UTC, leslietilling approved these changes

2021-05-14 12:37 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-05-14 12:38 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-05-14 19:10 UTC, merged