Add description with links for the Product settings
magento/merchdocs pull request #1247
Opened 2021-04-28 13:21 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

This pull request (PR) adds a description with links for the Product settings.

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/catalog/settings.html

2021-05-14 17:01 UTC, leslietilling requested changes
Editorial fixes

2021-05-14 17:01 UTC, leslietilling commented on src/catalog/settings.md
> +|[Gift options]({% link catalog/product-gift-options.md %})|Can be set at the product level to allow a gift message to be included during checkout.|
```suggestion
|[Gift options]({% link catalog/product-gift-options.md %})|Used to enable or disable a gift message option during checkout at the product level.|
```

2021-05-14 17:01 UTC, leslietilling commented on src/catalog/settings.md
> +|[Downloadable Information]({% link catalog/product-downloadable-information.md %})|Is used to generate the links to downloadable products and samples.|
```suggestion
|[Downloadable Information]({% link catalog/product-downloadable-information.md %})|Used to generate the links to downloadable products and samples.|
```

2021-05-14 20:42 UTC, EvheniiaKolkhiieva commented
Hi @leslietilling, thank you for the review :) 
I have implemented your suggestions, could you please approve?

2021-05-14 20:44 UTC, EvheniiaKolkhiieva commented on src/catalog/settings.md
> +|[Customizable Options]({% link catalog/settings-advanced-custom-options.md %})|Adds customizable options to a product.|
@leslietilling Could you please clarify what I need to change here? Seems your suggestion is the same with my

2021-05-17 14:39 UTC, leslietilling commented on src/catalog/settings.md
> +|[Customizable Options]({% link catalog/settings-advanced-custom-options.md %})|Adds customizable options to a product.|
I think this one was a GitHub UI glitch.  Ignore.

2021-05-17 14:40 UTC, leslietilling approved these changes

2021-05-25 11:22 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-05-25 11:23 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-05-25 16:02 UTC, closed without merging