Adding additional note to editing account information page
magento/merchdocs pull request #1251
Opened 2021-04-29 09:31 UTC by DmitryTsymbal

## Purpose of this pull request

PR contains minor adjustment for edit admin account information page.

## Affected documentation pages

- https://docs.magento.com/user-guide/stores/admin-account.html

2021-04-29 11:37 UTC, dmytro-ch requested changes

2021-04-29 11:37 UTC, dmytro-ch commented on src/stores/admin-account.md
> +   Please note: you should fill current admin password into **Your Password** field, each time you edit account information, to apply the changes.
```suggestion
   You should fill the current admin password into **Your Password** field, each time you edit account information, to apply the changes.
```

2021-04-29 11:46 UTC, dmytro-ch approved these changes

2021-05-06 14:39 UTC, dobooth approved these changes

2021-05-06 14:40 UTC, dobooth commented
@magento import code to magento-devdocs/merchdocs

2021-05-06 14:41 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1251`.

2021-05-11 12:46 UTC, closed without merging