Add the System Alerts block to the Customer Engagement Reporting page
magento/merchdocs pull request #1256
Opened 2021-04-30 14:16 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request:
- adds the System Alerts block to the Customer Engagement Reporting page
- adds new step to the Import Settings block

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/reports/customer-engagement.html

2021-05-14 17:24 UTC, leslietilling requested changes
Minor edits

2021-05-14 17:24 UTC, leslietilling commented on src/reports/customer-engagement.md
> +   1. To remove the /pub directory from image URLs in the catalog, set Remove /pub directory from URLs to “Yes”.
```suggestion
   1. To remove the /pub directory from image URLs in the catalog, set **Remove /pub directory from URLs** to `Yes`.
```

2021-05-14 17:24 UTC, leslietilling commented on src/reports/customer-engagement.md
>     1. To sync subscriber dales data, set **Enable Subscribers Sales Data Sync** to "Yes". This option is disabled by default due to the increased server load and sync times.
Let's fix this one too
```suggestion
   1. To sync subscriber dales data, set **Enable Subscribers Sales Data Sync** to `Yes`. (This option is disabled by default due to the increased server load and sync times.)
```

2021-05-14 17:24 UTC, leslietilling commented on src/reports/customer-engagement.md
> +## Configure System Alerts
```suggestion
## Configure system alerts
```

2021-05-14 17:24 UTC, leslietilling commented on src/reports/customer-engagement.md
> +1. To send in-app system messages to admin users when errors that may affect the dotdigital extension are detected, set **Enable System Messages** to "Yes".
```suggestion
1. To send system messages to Admin users when errors that could affect the dotdigital extension are detected, set **Enable System Messages** to `Yes`.
```

2021-05-14 17:24 UTC, leslietilling commented on src/reports/customer-engagement.md
> +1. To send system alert email notifications when errors that may affect the dotdigital extension are detected, set **Enable Email Notifications** to "Yes".
```suggestion
1. To send system alert email notifications when errors that could affect the dotdigital extension are detected, set **Enable Email Notifications** to `Yes`.
```

2021-05-14 17:24 UTC, leslietilling commented on src/reports/customer-engagement.md
> +1. Select the user role in the **Select Roles** field  who will receive email notifications.
```suggestion
1. For **Select Roles**, select the user role to determine who will receive email notifications.
```

2021-05-14 17:24 UTC, leslietilling commented on src/reports/customer-engagement.md
> +1. To specify the email notification frequency and the time interval for error reporting, set **Alert Frequency** to one of the options: 1 hour, 12 hours, 24 hours, 48 hours, 72 hours.
```suggestion
1. To specify the email notification frequency and the time interval for error reporting, set **Alert Frequency** to one of the following options:
   * 1 hour
   * 12 hours
   * 24 hours
   * 48 hours
   * 72 hours
```

2021-05-18 14:01 UTC, ZhovnirMaria commented
@leslietilling hi! 👋 
Thank you, done ✅

2021-05-18 18:03 UTC, leslietilling approved these changes

2021-05-19 12:26 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-05-19 12:27 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-05-25 17:13 UTC, dobooth commented
Auto-close failed due to merge conflict.

2021-05-25 17:13 UTC, closed without merging