Add topic about reorder from the storefront
magento/merchdocs pull request #1260
Opened 2021-05-03 12:20 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

This pull request (PR) adds topic about Reorder from the Storefront

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/customers/account-dashboard-my-orders.html

2021-05-25 18:55 UTC, leslietilling requested changes
Minor edits

2021-05-25 18:55 UTC, leslietilling commented on src/customers/account-dashboard-reorders.md
> +For the reorder to be available, make sure the [_Allow Reorder_]({% link sales/reorders-allow.md %}) configuration option is enabled.
```suggestion
Reorders are available to customers when the [_Allow Reorder_]({% link sales/reorders-allow.md %}) configuration option is enabled.
```

2021-05-25 18:55 UTC, leslietilling commented on src/customers/account-dashboard-reorders.md
> +User will be redirected to the [shopping cart]({% link quick-tour/shopping-cart.md %}), and all products are added to the cart
```suggestion
Customer is redirected to the [shopping cart]({% link quick-tour/shopping-cart.md %}), and all products are added to the cart
```

2021-05-25 18:55 UTC, leslietilling commented on src/customers/account-dashboard-reorders.md
> +User will be redirected to the cart, and all products are added to the cart
```suggestion
Customer is redirected to the cart, and all products are added to the cart
```

2021-05-25 18:55 UTC, leslietilling commented on src/customers/account-dashboard-reorders.md
> +The Reorder button will not appear on the My Orders and View Order pages.
```suggestion
The _Reorder_ button does not appear on the My Orders and View Order pages.
```

2021-05-25 18:55 UTC, leslietilling commented on src/customers/account-dashboard-reorders.md
> +If the cart is not empty and the user clicks Reorder (from the My Orders or Order View page), the existing products will remain in the cart with the added reorder products.
```suggestion
If the cart is not empty and the customer clicks **Reorder** (from the My Orders or Order View page), the existing products remain in the cart with the added reorder products.
```

2021-05-26 13:27 UTC, EvheniiaKolkhiieva commented
Hi @leslietilling , thank you for reviewing ☀️
I have implemented your suggestions, could you please approve this PR?
Thank you!

2021-05-26 13:27 UTC, EvheniiaKolkhiieva commented on src/customers/account-dashboard-reorders.md
> +If the cart is not empty and the user clicks Reorder (from the My Orders or Order View page), the existing products will remain in the cart with the added reorder products.
Done ✅

2021-05-26 13:27 UTC, EvheniiaKolkhiieva commented on src/customers/account-dashboard-reorders.md
> +The Reorder button will not appear on the My Orders and View Order pages.
Done ✅

2021-05-26 13:27 UTC, EvheniiaKolkhiieva commented on src/customers/account-dashboard-reorders.md
> +User will be redirected to the cart, and all products are added to the cart
Done ✅

2021-05-26 13:27 UTC, EvheniiaKolkhiieva commented on src/customers/account-dashboard-reorders.md
> +User will be redirected to the [shopping cart]({% link quick-tour/shopping-cart.md %}), and all products are added to the cart
Done ✅

2021-05-26 13:27 UTC, EvheniiaKolkhiieva commented on src/customers/account-dashboard-reorders.md
> +For the reorder to be available, make sure the [_Allow Reorder_]({% link sales/reorders-allow.md %}) configuration option is enabled.
Done ✅

2021-05-26 16:34 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-26 20:23 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-26 20:25 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-05-27 21:30 UTC, merged