Column description for the Shipment page
magento/merchdocs pull request #1262
Opened 2021-05-03 14:34 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request adds missing columns description for the Shipment page

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/sales/shipments.html

2021-05-25 11:31 UTC, dobooth approved these changes

2021-05-25 11:31 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-05-25 11:32 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-05-25 18:58 UTC, leslietilling requested changes

2021-05-25 18:58 UTC, leslietilling commented on src/sales/shipments.md
> +|Select|Select the checkbox to select the quote(s) to be subject to an action, or use the selection control in the column header. Options: Select All / Deselect All|
```suggestion
|Select|Select the checkbox for each quote to be subject to an action, or use the selection control in the column header. Options: Select All / Deselect All|
```

2021-05-25 18:58 UTC, leslietilling commented on src/sales/shipments.md
> +### Additional Columns
```suggestion
### Additional columns
```

2021-05-26 16:37 UTC, leslietilling approved these changes

2021-05-26 16:37 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-26 20:53 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-26 20:54 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-05-27 21:30 UTC, merged