Expanding of the benefits of the Company Accounts
magento/merchdocs pull request #1270
Opened 2021-05-05 08:35 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

This pull request (PR) :
- Fixes the https://github.com/magento/merchdocs/issues/1255
- Describes what is Company Accounts
- Describes the benefits of the Company Accounts
- Adds useful links to other topics 

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/customers/account-companies.html

2021-05-27 21:48 UTC, leslietilling requested changes
Just some edits for style and clarity

2021-05-27 21:48 UTC, leslietilling commented on src/customers/account-companies.md
> +By introducing B2B company accounts to your Magento 2 store, you can simplify the corporate shopping, let companies create multiple sub-accounts with flexible permissions based on user roles in the o
```suggestion
When you incorporate B2B company accounts in your Magento store, you can simplify the corporate shopping by enabling companies to create multiple sub-accounts with flexible permissions based on user roles in their organization. Depending on the customer groups of the company, a store administrator can adjust promotions and prices to suit their needs, and create highly customized offers that cater to the shoppers’ demands and increase orders.
```

2021-05-27 21:48 UTC, leslietilling commented on src/customers/account-companies.md
> +Advantage of Magento 2 Company Account:
```suggestion
Advantages of  a company account:
```

2021-05-27 21:48 UTC, leslietilling commented on src/customers/account-companies.md
> +1. [B2B]({% link configuration/general/b2b-features.md  %}) Company Account offers unlimited users and the creation of additional accounts, thereby simplifying corporate purchases.
This should really be an unordered list
```suggestion
1. - A [B2B]({% link configuration/general/b2b-features.md  %}) company account offers unlimited users and the creation of additional accounts, thereby simplifying corporate purchases.
```

2021-05-27 21:48 UTC, leslietilling commented on src/customers/account-companies.md
> +1. There is an ability to build a smart B2B company account hierarchy with different [roles and permissions] ({% link customers/account-company-roles-permissions.md %}) as placing orders.
```suggestion
- Includes support for a "smart" company account hierarchy with different [roles and permissions] ({% link customers/account-company-roles-permissions.md %}) for placing orders.
```

2021-05-27 21:48 UTC, leslietilling commented on src/customers/account-companies.md
> +1. Allows to increase income by offering a [Company Store Credits] ({% link customers/account-dashboard-company-credit.md %}) payment method.
```suggestion
- Provides a mechanism for merchants to increase income by offering [company store credit] ({% link customers/account-dashboard-company-credit.md %}) as a payment method.
```

2021-05-27 21:48 UTC, leslietilling commented on src/customers/account-companies.md
> +1. Permit [managing] ({% link customers/account-company-manage.md %}) all Company Accounts in Magento Admin.
```suggestion
1. Supports the [management] ({% link customers/account-company-manage.md %}) of all company accounts in the Admin.
```

2021-05-27 21:48 UTC, leslietilling commented on src/customers/account-companies.md
> +The Companies grid lists all active company accounts and pending requests, regardless of status setting. It also provides the tools needed to create and [manage]({% link customers/account-company-man
```suggestion
The _Companies_ grid lists all active company accounts and pending requests, regardless of status setting. It also provides the tools needed to [create]({% link customers/account-company-create.md %}) and [manage]({% link customers/account-company-manage.md %}) company accounts. Use the standard [grid controls]({% link stores/admin-grid-controls.md %}) to filter the list, and adjust the [column layout]({% link stores/admin-grid-layout.md %}). For a list of column descriptions, see the _Column Descriptions_ section in [Managing Company Accounts]({% link customers/account-company-manage.md %}).
```

2021-05-27 21:48 UTC, leslietilling commented on src/customers/account-companies.md
> +Company accounts can be set up from the storefront or from the Admin. By default, the ability to create company accounts from the storefront is enabled. If allowed in the configuration, a visitor to
```suggestion
Customers can create a new company accounts from the storefront, or a merchant can create one from the Admin. By default, the ability to create company accounts from the storefront is enabled. If allowed by the configuration, a visitor to the store can request to open a company account. After the company account is approved, the company administrator can set up the company structure and users with various levels of permission.
```

2021-05-28 11:37 UTC, EvheniiaKolkhiieva commented
Hello @leslietilling , thank you a lot for reviewing.

I have implemented your suggestions, could you please approve this PR? 
Thank you 😊

2021-05-28 11:37 UTC, EvheniiaKolkhiieva commented on src/customers/account-companies.md
> +Company accounts can be set up from the storefront or from the Admin. By default, the ability to create company accounts from the storefront is enabled. If allowed in the configuration, a visitor to
Done ✅

2021-05-28 11:37 UTC, EvheniiaKolkhiieva commented on src/customers/account-companies.md
> +The Companies grid lists all active company accounts and pending requests, regardless of status setting. It also provides the tools needed to create and [manage]({% link customers/account-company-man
Done ✅

2021-05-28 11:37 UTC, EvheniiaKolkhiieva commented on src/customers/account-companies.md
> +1. Permit [managing] ({% link customers/account-company-manage.md %}) all Company Accounts in Magento Admin.
Done ✅

2021-05-28 11:37 UTC, EvheniiaKolkhiieva commented on src/customers/account-companies.md
> +1. Allows to increase income by offering a [Company Store Credits] ({% link customers/account-dashboard-company-credit.md %}) payment method.
Done ✅

2021-05-28 11:37 UTC, EvheniiaKolkhiieva commented on src/customers/account-companies.md
> +1. There is an ability to build a smart B2B company account hierarchy with different [roles and permissions] ({% link customers/account-company-roles-permissions.md %}) as placing orders.
Done ✅

2021-05-28 11:37 UTC, EvheniiaKolkhiieva commented on src/customers/account-companies.md
> +Advantage of Magento 2 Company Account:
Done ✅

2021-05-28 11:38 UTC, EvheniiaKolkhiieva commented on src/customers/account-companies.md
> +By introducing B2B company accounts to your Magento 2 store, you can simplify the corporate shopping, let companies create multiple sub-accounts with flexible permissions based on user roles in the o
Done ✅

2021-05-28 14:45 UTC, leslietilling approved these changes

2021-05-28 14:55 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-28 14:56 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-05-28 16:30 UTC, merged