Issue#923 Update VAT configuration page
magento/merchdocs pull request #1274
Opened 2021-05-05 13:48 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request describes the relationship between the tax rate and the tax rule creation process.  The **Step 1** involves the confirmation of the needed tax class/rate in order to complete **Step 2**.

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/tax/vat-configure.html

2021-05-27 22:08 UTC, leslietilling requested changes
Just some edits for style and clarity

2021-05-27 22:08 UTC, leslietilling commented on src/tax/vat-configure.md
> +1. Enter the **Tax Identifier** for the new tax class. All tax rates displayed in the **Tax Rate** field of the **Tax Rule Information**, for each tax rules.
```suggestion
1. Enter the **Tax Identifier** for the new tax class.

   All tax rates are displayed in the _Tax Rate_ field in the _Tax Rule Information_ when you create tax rules.
```

2021-05-28 08:33 UTC, ZhovnirMaria commented
Thanks, @leslietilling 😊
Done✅

2021-05-28 14:22 UTC, leslietilling approved these changes

2021-05-28 14:28 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-28 15:27 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-28 15:36 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-28 15:37 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-05-28 16:30 UTC, merged