magento/merchdocs#60: Update product review information
magento/merchdocs pull request #1276
Opened 2021-05-06 12:19 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request updates product review information:
 - Enable Magento Product Reviews
 - Moderate Reviews
 - Ratings

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/magento-product-reviews-config.html
https://docs.magento.com/user-guide/marketing/magento-product-reviews-moderate.html
https://docs.magento.com/user-guide/stores/attributes-rating.html

2021-05-27 22:15 UTC, leslietilling requested changes
Minor edits

2021-05-27 22:15 UTC, leslietilling commented on src/marketing/magento-product-reviews-moderate.md
> +1. Also, the admin can moderate the **Detailed Rating**, **Nickname**, **Summary of Review** fields.
```suggestion
1. If needed, change the values for **Detailed Rating**, **Nickname**, and **Summary of Review** .
```

2021-05-27 22:15 UTC, leslietilling commented on src/stores/attributes-rating.md
> +1. The average rating for all reviews is displayed for each product on the catalog product grid page.
This is not really a step, more of a final result
```suggestion
   The average rating for all reviews is displayed for each product on the catalog product grid page.
```

2021-05-28 08:35 UTC, ZhovnirMaria commented
Thanks, @leslietilling 😊
Done✅

2021-05-28 14:18 UTC, leslietilling approved these changes

2021-05-28 14:18 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-28 14:52 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-28 14:54 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-05-28 16:30 UTC, merged