Add Braintree block to the Sales Menu page
magento/merchdocs pull request #1277
Opened 2021-05-06 13:45 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request:
- Add Braintree block to the Sales Menu page
- adds Braintree page to the storefront

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages
https://docs.magento.com/user-guide/sales.html
https://docs.magento.com/user-guide/payment/braintree.html

2021-05-27 22:21 UTC, leslietilling requested changes
Minor edit

2021-05-27 22:21 UTC, leslietilling commented on src/sales/sales-menu.md
> +On the Braintree Virtual Terminal page, the admin can accept the payment for the selected amount. To available the terminal feature customer should configure basic [Braintree settings]({% link paymen
```suggestion
On the Braintree Virtual Terminal page, an Admin user can accept the payment for the selected amount. To make  the terminal feature available, a merchant should configure basic [Braintree settings]({% link payment/braintree.md %}). Braintree offers a fully customizable checkout experience with fraud detection and PayPal integration.
```

2021-05-27 22:22 UTC, leslietilling commented on src/_data/toc/sales.yml
> +  - label: Braintree
If this page is already in a toc file, it cannot be used a second time (causes problems with nav switching)

2021-05-28 14:19 UTC, leslietilling approved these changes

2021-05-28 14:19 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-28 14:57 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-28 14:59 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-05-28 16:30 UTC, merged