Update the creating category rules page
magento/merchdocs pull request #1278
Opened 2021-05-07 13:03 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request updates the creating category rules page

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/catalog/category-product-rules.html

2021-05-27 22:33 UTC, leslietilling requested changes

2021-05-27 22:33 UTC, leslietilling commented on src/catalog/category-product-rules.md
>  1. Click <span class="btn">Add Condition</span> and do the following:
If you convert bullet items to steps at same level, you have to remove this part

```suggestion
1. Click <span class="btn">Add Condition</span>.
```

2021-05-27 22:33 UTC, leslietilling commented on src/catalog/category-product-rules.md
> +      |`AND`|The rule applies to products, where all the conditions coincide.|
```suggestion
      |`AND`|The rule applies to products, where all the conditions are met.|
```

2021-05-27 22:33 UTC, leslietilling commented on src/catalog/category-product-rules.md
> +      |`OR`|The rule applies to products, where at least one condition coincides.|
```suggestion
      |`OR`|The rule applies to products, where at least one condition is met.|
```

2021-05-28 08:34 UTC, ZhovnirMaria commented
Thanks, @leslietilling 😊
Done✅

2021-05-28 14:27 UTC, leslietilling approved these changes

2021-05-28 14:27 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-28 15:30 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-05-28 16:30 UTC, merged