Describe how to update the reward points balance
magento/merchdocs pull request #1306
Opened 2021-05-19 12:12 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request describes how to update the reward points balance from the admin panel

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/customers/account-dashboard-reward-points.html?itm_source=merchdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=Reward%20Points

2021-06-07 21:14 UTC, leslietilling requested changes
Some basic edits

2021-06-07 21:14 UTC, leslietilling commented on src/customers/account-dashboard-reward-points.md
> +1. In the **Customer Information** panel, choose the **Reward Points** section.
```suggestion
1. Under _Customer Information_, choose the **Reward Points** section.
```

2021-06-07 21:14 UTC, leslietilling commented on src/customers/account-dashboard-reward-points.md
> +    - Subscribe for Points Expiration Notifications
```suggestion
1. Optionally, subscribe the customer to _Reward Points Notifications_:

    - **Subscribe for Balance Updates**
    - **Subscribe for Points Expiration Notifications**
```

2021-06-07 21:14 UTC, leslietilling commented on src/customers/account-dashboard-reward-points.md
> +|[Rate]({% link marketing/reward-exchange-rates.md %})|Reward exchange rate|
Better to put the link in the description

```suggestion
|Rate|[Reward exchange rate]({% link marketing/reward-exchange-rates.md %})|
```

2021-06-07 21:14 UTC, leslietilling commented on src/customers/account-dashboard-reward-points.md
> +|Website|Website to which the reward points history assigned|
```suggestion
|Website|Website to which the reward points history is assigned|
```

2021-06-07 21:14 UTC, leslietilling commented on src/customers/account-dashboard-reward-points.md
> +|Reason|Reasons for awarding points:<br>**Making purchases** — every time you make a purchase you can earn points.<br>**Registering on the site** - accrued once upon registration.<br>**Subscribing to
```suggestion
|Reason|Reasons for awarding points:<br>**Making purchases** — Every time the customer makes a purchase they can earn points.<br>**Registering on the site** - Accrued upon registration (once).<br>**Subscribing to a newsletter** - Accrued for the first time subscription (once).<br>**Sending Invitations** — Earn points by inviting their friends to join the site.<br>**Converting Invitations to Customer** — Earn points for every invitation they send out, leading friends registering on the site.<br>**Converting Invitations to Order** — Earn points for each sale resulting from a sent invitation.<br>**Review Submission** — Earn points for submitting product reviews.|
```

2021-06-08 15:06 UTC, leslietilling approved these changes

2021-06-08 15:07 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-06-11 15:38 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-06-11 15:39 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-06-14 14:10 UTC, merged