Add columns to the Billing Agreements page
magento/merchdocs pull request #1329
Opened 2021-06-02 09:47 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request adds columns to the Billing Agreements page

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/sales/billing-agreements.html

2021-06-03 15:10 UTC, dobooth requested changes

2021-06-03 15:10 UTC, dobooth commented on src/sales/billing-agreements.md
> +Every time when a customer places an order using a billing agreement, Magento 2 sends the billing agreement reference ID and sales order billing information to PayPal. The relevant information data r
```suggestion
When a customer places an order using a billing agreement, Magento sends the billing agreement reference ID and sales order billing information to PayPal. The relevant information data records in the customer's account.
```
I am not sure what the last sentence here means. Can you rewrite please?

2021-06-23 11:53 UTC, dobooth commented
@ZhovnirMaria

2021-06-24 08:31 UTC, ZhovnirMaria commented
@dobooth Hi, I tried to rephrase the sentence, please let me know if there is any issues😊

2021-06-24 11:36 UTC, dobooth approved these changes

2021-06-24 11:36 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-06-24 11:37 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-06-29 15:10 UTC, merged