Update fields for the Scheduling an Import page
magento/merchdocs pull request #1332
Opened 2021-06-03 13:56 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request updates fields for the Scheduling an Import page

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/system/data-schedule-import.html

2021-06-24 18:53 UTC, leslietilling requested changes
Some adjustments needed.

2021-06-24 18:53 UTC, leslietilling commented on src/system/data-schedule-import.md
> +      For the `Customer Finances`, `Customers Main File`, `Customers and Addresses` entity’s types are displayed such import behaviors as: Add/Update Complex Data, Delete Entities, Custom Action.
This should be a note callout and needs some tweaking on grammar and formatting.

```suggestion
      {:.bs-callout-info}
      For the _Advanced Pricing_, _Products_, _Customers and Addresses (single file)_, and _Stock Sources_ entity types, these additional import behaviors displayed: Add/Update, Replace, and Delete. For the _Customer Finances_, _Customers Main File_, and _Customers and Addresses_ entity types, these additional import behaviors displayed: Add/Update Complex Data, Delete Entities, and Custom Action.
```

2021-06-24 18:53 UTC, leslietilling commented on src/system/data-schedule-import.md
> +Import Behavior | Defines how complex data is handled if entities, which are being imported, already exist in the database. Complex data for products include categories, websites, custom options, tie
```suggestion
Import Behavior | Defines how complex data is handled if the entities being imported already exist in the database. Complex data for products include categories, websites, custom options, tier prices, related products, up-sells, cross-sells, and associated products data. Complex data for customers include addresses. Options:<br>**Add/Update Complex Data** - The new complex data are added or updated to the existing complex data for existing entries in the database. This is the default value.<br>**Replace** - The existing complex data for the existing entities are replaced.<br>**Delete Entities** - If imported entities already exist in the database, they are deleted from the database.<br>**Custom Action** - The existing complex entities are customized during the import process.
```

2021-06-29 16:17 UTC, leslietilling approved these changes

2021-06-29 16:18 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-12 15:20 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-12 15:21 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-13 17:50 UTC, merged