Add field descriptions to the content block pages
magento/merchdocs pull request #1336
Opened 2021-06-10 12:39 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request adds field descriptions to the content block pages

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/design/layout-update-place-block.html
https://docs.magento.com/user-guide/cms/page-hierarchy-configure.html

2021-06-17 16:39 UTC, leslietilling requested changes

2021-06-24 09:02 UTC, ZhovnirMaria commented on src/design/layout-update-place-block.md
> +|Field|Description|
hmm, I agree with you in this case better remove these columns.

2021-06-24 12:10 UTC, dobooth approved these changes

2021-06-24 12:10 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-06-24 12:11 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-06-24 18:54 UTC, leslietilling approved these changes

2021-06-29 15:10 UTC, merged