Update the Related Product Rules page and add columns description
magento/merchdocs pull request #1337
Opened 2021-06-11 10:01 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request:
- updates the Related Product Rules page;
- adds columns description;

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- ...
- ...

## Links to Magento source code or PRs

- ...
- ...

## Additional information

https://docs.magento.com/user-guide/marketing/product-related-rules.html

2021-06-17 16:43 UTC, leslietilling requested changes
Just some minor edits. Some descriptions are complete sentences, so would need a period.

2021-06-17 16:43 UTC, leslietilling commented on src/marketing/product-related-rules.md
> +|Start|Use the dynamic calendar fields (To: and From:) to filter the list based on the start date for the rule as defined when the rule was created|
```suggestion
|Start|Use the dynamic calendar fields (_To:_ and _From:_) to filter the list based on the start date for the rule as defined when the rule was created.|
```

2021-06-17 16:43 UTC, leslietilling commented on src/marketing/product-related-rules.md
> +|End|Use the dynamic calendar fields (To: and From:) to filter the list based on the end date for the rule as defined when the rule was created|
```suggestion
|End|Use the dynamic calendar fields (_To:_ and _From:_) to filter the list based on the end date for the rule as defined when the rule was created.|
```

2021-06-17 16:43 UTC, leslietilling commented on src/marketing/product-related-rules.md
> +|Priority|Enter text in this field to filter the list based on the priority defined for a rule|
```suggestion
|Priority|Enter text in this field to filter the list based on the priority defined for a rule.|
```

2021-06-17 16:43 UTC, leslietilling commented on src/marketing/product-related-rules.md
> +|Applies To|This option filters the list of rules that apply to: `Related Products`, `Up-sells`, `Cross-sells`|
```suggestion
|Applies To|This option filters the list of rules that apply to `Related Products`, `Up-sells`, and `Cross-sells`.|
```

2021-06-17 16:43 UTC, leslietilling commented on src/marketing/product-related-rules.md
> +|Status|Use this option to filter the list based on rule status, `Active` or `Inactive`|
```suggestion
|Status|Use this option to filter the list based on rule status, `Active` or `Inactive`.|
```

2021-06-24 18:55 UTC, leslietilling approved these changes

2021-06-24 18:56 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-06-24 21:43 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-06-24 21:44 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-06-29 15:10 UTC, merged