Update the Setting Up a Gift Registry columns
magento/merchdocs pull request #1339
Opened 2021-06-14 14:22 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request updates the Setting Up a Gift Registry columns

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/gift-registry-create.html?itm_source=merchdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=Setting%20Up%20a%20Gift%20Registry

2021-07-01 15:39 UTC, leslietilling requested changes
Just some edits for clarity and formatting.

2021-07-01 15:39 UTC, leslietilling commented on src/marketing/gift-registry-create.md
> +|Role|The role that identifies who the gift is for. <br/>Set **Is Searcheable** to: Yes / No <br/>Set **Is Listed** to: Yes / No <br/>Click **Add New Option** to add more conditions to the drop-down
```suggestion
|Role|The role that identifies the gift recipient. For example, `Bride`, `Groom`, or `Partner`.<br/>**Is Searcheable** - Set to `Yes `/ `No` <br/>**Is Listed** - Set to `Yes` / `No` <br/>**Add New Option** - Click  to add more conditions to the drop-down menu:<br/>**Code** - A unique name to identify the attribute internally.<br/>**Label** - The name that identifies the attribute in the customer’s account dashboard.<br/>**Is Default** - Set this switch to select the default condition.<br/>**Delete Option** - Click to delete the option.|
```

2021-07-02 07:52 UTC, ZhovnirMaria commented on src/marketing/gift-registry-create.md
> +|Role|The role that identifies who the gift is for. <br/>Set **Is Searcheable** to: Yes / No <br/>Set **Is Listed** to: Yes / No <br/>Click **Add New Option** to add more conditions to the drop-down
@leslietilling Thank you, done  ☑️

2021-07-12 15:40 UTC, leslietilling approved these changes

2021-07-12 15:42 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-12 15:43 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-13 17:50 UTC, merged