Describe the Layout Updates Options columns for the "Using a Widget to Position a Block" page
magento/merchdocs pull request #1341
Opened 2021-06-15 10:16 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request describes the Layout Updates Options columns for the "Using a Widget to Position a Block" page

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/cms/widget-static-block.html

2021-07-12 15:58 UTC, leslietilling requested changes
minor edits

2021-07-12 15:58 UTC, leslietilling commented on src/cms/widget-static-block.md
> +### Layout Updates Options
```suggestion
### Layout update options
```

2021-07-12 15:58 UTC, leslietilling commented on src/cms/widget-static-block.md
> +|Non-Anchor Categories|Displays the widget on the non-anchor category page. Options:<br/>**Categories** - Categories where the anchor will be displayed. Options: All / Specific Categories<br/>**Conta
```suggestion
|Non-Anchor Categories|Displays the widget on the non-anchor category page. Options:<br/>**Categories** - Categories where the anchor is displayed. Options: All / Specific Categories<br/>**Container** - Set container to the part of the page layout where you want to display the widget.<br/>**Template** - Determines the theme of the layout.|
```

2021-07-12 15:58 UTC, leslietilling commented on src/cms/widget-static-block.md
> +|Anchor Categories|Displays the widget on the anchor category page. Options:<br/>**Categories** - Categories where the anchor will be displayed. Options: All / Specific Categories<br/>**Container** -
```suggestion
|Anchor Categories|Displays the widget on the anchor category page. Options:<br/>**Categories** - Categories where the anchor is displayed. Options: All / Specific Categories<br/>**Container** - Set container to the part of the page layout where you want to display the widget.<br/>**Template** - Determines the theme of the layout.|
```

2021-07-12 15:58 UTC, leslietilling commented on src/cms/widget-static-block.md
> +|All Product Types|Displays the widget on either a specific type of product page, or on all product pages. Options:<br/>**Products** - Products for which the widget is displayed. Options: All / Speci
```suggestion
|All Product Types|Displays the widget on either a specific type of product page, or on all product pages. Options:<br/>**Products** - Products for which the widget is displayed. Options: All / Specific Products<br/>**Container** - Set container to the part of the page layout where you want to display the widget.<br/>**Template** - Determines the theme of the layout.|
```

2021-07-12 15:58 UTC, leslietilling commented on src/cms/widget-static-block.md
> +|All Pages|Displays the widget on all pages. Options:<br/>**Container** - Set container to the part of the page layout where the widget is to appear.<br/>**Template** - Determines the theme of the la
```suggestion
|All Pages|Displays the widget on all pages. Options:<br/>**Container** - Set container to the part of the page layout where you want to display the widget.<br/>**Template** - Determines the theme of the layout.|
```

2021-07-12 15:58 UTC, leslietilling commented on src/cms/widget-static-block.md
> +|Specified Page|Displays the widget on a specific page. Options:<br/>**Page** - Pages for which the widget is displayed.<br/>**Container** - Set container to the part of the page layout where the wid
```suggestion
|Specified Page|Displays the widget on a specific page. Options:<br/>**Page** - Pages for which the widget is displayed.<br/>**Container** - Set container to the part of the page layout where you want to display the widget.<br/>**Template** - Determines the theme of the layout.|
```

2021-07-12 15:58 UTC, leslietilling commented on src/cms/widget-static-block.md
> +|Page Layouts|Displays the widget on pages with a certain layout. Options:<br/>**Page** - Pages for which the widget is displayed.<br/>**Container** - Set container to the part of the page layout whe
```suggestion
|Page Layouts|Displays the widget on pages with a certain layout. Options:<br/>**Page** - Pages for which the widget is displayed.<br/>**Container** - Set container to the part of the page layout where you want to display the widget.<br/>**Template** - Determines the theme of the layout.|
```

2021-07-15 15:46 UTC, leslietilling approved these changes

2021-07-15 15:48 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-15 15:54 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-15 15:55 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-16 13:20 UTC, merged