Describe how to add an item to the gift register
magento/merchdocs pull request #1347
Opened 2021-06-16 12:45 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request describes how to add an item to the gift register

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/gift-registries.html

2021-07-01 18:06 UTC, leslietilling requested changes
If we document a workflow on the storefront, we are describing the required action of the customer to the store merchant. So in these cases, it is a third-person procedure. We have not been consistent with this in the guide but it is something that we want to address going forward.

2021-07-01 18:06 UTC, leslietilling commented on src/marketing/gift-registries.md
> +## Add an item to the Gift Register
```suggestion
## Add an item to a gift registry on the storefront
```

2021-07-01 18:06 UTC, leslietilling commented on src/marketing/gift-registries.md
> +1. Open the product that you want to add to the gift registry event.
```suggestion
1. The customer opens the product that they want to add to the gift registry event.
```

2021-07-01 18:06 UTC, leslietilling commented on src/marketing/gift-registries.md
> +1. Click <span class="btn">Add to Cart</span>.
```suggestion
1. Clicks/taps <span class="btn">Add to Cart</span>.
```

2021-07-01 18:06 UTC, leslietilling commented on src/marketing/gift-registries.md
> +1. Click <span class="btn">View and Edit Cart</span> on the Mini Cart.
```suggestion
1. Clicks/taps <span class="btn">View and Edit Cart</span> on the mini cart.
```

2021-07-01 18:06 UTC, leslietilling commented on src/marketing/gift-registries.md
> +1. On the Shopping Cart page select the event you need and click <span class="btn">Add All To Gift Registry</span>.
```suggestion
1. On the Shopping Cart page, selects the event they want and clicks/taps <span class="btn">Add All To Gift Registry</span>.
```

2021-07-01 18:06 UTC, leslietilling commented on src/marketing/gift-registries.md
> +1. Items will be added to the gift register of the selected event.
This is a result and not a step

```suggestion
   Items are added to the gift registry of the selected event.
```

2021-07-02 08:14 UTC, ZhovnirMaria commented on src/marketing/gift-registries.md
> +1. Items will be added to the gift register of the selected event.
Done, thanks 😊

2021-07-12 16:00 UTC, leslietilling approved these changes

2021-07-12 16:01 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-12 17:25 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-07-12 17:26 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-07-13 17:50 UTC, merged