Add topic about how to update product attribute in bulk
magento/merchdocs pull request #1352
Opened 2021-06-23 17:18 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

This pull request (PR) adds steps to update product attribute in bulk

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/catalog/product-attributes.html

2021-07-12 16:10 UTC, leslietilling requested changes
minor edits

2021-07-12 16:10 UTC, leslietilling commented on src/stores/bulk-product-attribute-update.md
> +Use the "Update Attributes" tool to change one or more attributes in your products. This tool helps to massively transform the desired parts of the products.
```suggestion
Use the _Update Attributes_ tool to change one or more attributes in your products. This tool allows you to apply significant changes across a large group of products.
```

2021-07-12 16:10 UTC, leslietilling commented on src/stores/bulk-product-attribute-update.md
> +1. Update the attribute, advanced inventory or website data for product you want.
```suggestion
1. Update the attribute, advanced inventory, or website data for the selected products, according to your needs.
```

2021-07-12 16:10 UTC, leslietilling commented on src/stores/bulk-product-attribute-update.md
> +1. When finish, click <span class="btn">Save</span>.
```suggestion
1. When finished, click <span class="btn">Save</span>.
```

2021-07-12 16:10 UTC, leslietilling commented on src/stores/bulk-product-attribute-update.md
> +    _Bulk Updating Attribute_
```suggestion
    _Bulk updating for attributes_
```

2021-07-12 16:10 UTC, leslietilling commented on src/stores/bulk-product-attribute-update.md
> +    _Select products to attribute update_
```suggestion
    _Select products to be updated_
```

2021-07-12 16:10 UTC, leslietilling commented on src/stores/bulk-product-attribute-update.md
> +title: Bulk Updating Attributes
```suggestion
title: Bulk Updates for Product Attributes
```

2021-07-12 16:10 UTC, leslietilling commented on src/_data/toc/catalog.yml
> +  - label: Bulk Updating Attributes
```suggestion
  - label: Bulk Updates for Product Attributes
```

2021-07-13 08:16 UTC, EvheniiaKolkhiieva commented
Hi @leslietilling , thank you for reviewing. I have implemented your edits, could you please approve this PR?
Thank you! :)

2021-07-13 08:16 UTC, EvheniiaKolkhiieva commented on src/_data/toc/catalog.yml
> +  - label: Bulk Updating Attributes
Done ✅

2021-07-13 08:16 UTC, EvheniiaKolkhiieva commented on src/stores/bulk-product-attribute-update.md
> +title: Bulk Updating Attributes
Done ✅

2021-07-13 08:16 UTC, EvheniiaKolkhiieva commented on src/stores/bulk-product-attribute-update.md
> +    _Select products to attribute update_
Done ✅

2021-07-13 08:16 UTC, EvheniiaKolkhiieva commented on src/stores/bulk-product-attribute-update.md
> +    _Bulk Updating Attribute_
Done ✅

2021-07-13 08:17 UTC, EvheniiaKolkhiieva commented on src/stores/bulk-product-attribute-update.md
> +1. When finish, click <span class="btn">Save</span>.
Done ✅

2021-07-13 08:17 UTC, EvheniiaKolkhiieva commented on src/stores/bulk-product-attribute-update.md
> +1. Update the attribute, advanced inventory or website data for product you want.
Done ✅

2021-07-13 08:17 UTC, EvheniiaKolkhiieva commented on src/stores/bulk-product-attribute-update.md
> +Use the "Update Attributes" tool to change one or more attributes in your products. This tool helps to massively transform the desired parts of the products.
Done ✅

2021-07-13 15:03 UTC, leslietilling approved these changes

2021-07-13 15:06 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-13 16:37 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-07-13 16:38 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-07-13 17:50 UTC, merged