Add new topic to describe how to allow multiple admin login
magento/merchdocs pull request #1357
Opened 2021-06-25 08:28 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request adds a new topic to describe how to allow multiple admin login

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

2021-06-28 12:48 UTC, dobooth commented
Any reason we shouldn't just add this to https://docs.magento.com/user-guide/stores/admin-signin.html?

2021-06-28 13:13 UTC, ZhovnirMaria commented
Hi, @dobooth 
Hmm, you're right, if you don’t mind, I can just add this as a new block to the existing Admin Login page. When I started working on this topic, it seemed to me that this could be taken out as a separate topic.

2021-06-29 10:45 UTC, ZhovnirMaria commented
Hi, @dobooth. I have added this topic as a part of the https://docs.magento.com/user-guide/stores/admin-signin.html page. Please check, thanks 😊

2021-07-12 16:25 UTC, leslietilling requested changes
edits needed

2021-07-12 16:25 UTC, leslietilling commented on src/stores/admin-signin.md
> +## Allow Multiple Admin Login
```suggestion
## Allow multiple Admin logins
```

2021-07-12 16:25 UTC, leslietilling commented on src/stores/admin-signin.md
> +The admin manages the orders, customers, products, shipping, and payments functionality. The default configuration is set to not allowing the admin account sharing for security purposes. Multiple adm
This function actually determines if an account can be logged in at the same time from different devices. 

```suggestion
The Admin provides access to manage the orders, customers, products, shipping, and payments functionality. The default configuration is set to disallow multiple logins for an Admin user account as a security best practice. However, you can change this setting to allow Admin users to be logged in from multiple devices if that is needed to accommodate your business workflows.
```

2021-07-12 16:25 UTC, leslietilling commented on src/stores/admin-signin.md
> +1. Set `Yes` in the **Admin Account Sharing** field.
```suggestion
1. For **Admin Account Sharing**, select `Yes`.
```

2021-07-12 16:25 UTC, leslietilling commented on src/stores/admin-signin.md
> +1. On the _Admin_ sidebar, go to **Stores** > **Configuration**.
```suggestion
1. On the _Admin_ sidebar, go to **Stores** > _Settings_ > **Configuration**.
```

2021-07-12 16:25 UTC, leslietilling commented on src/stores/admin-signin.md
> +1. Under **Advanced**, select **Admin**.
```suggestion
1. In the left panel, expand **Advanced** and choose **Admin**.
```

2021-07-12 16:25 UTC, leslietilling commented on src/stores/admin-signin.md
> +1. Expand the **Security** section.
```suggestion
1. Expand ![Expansion selector]({% link images/images/btn-expand.png %}) the **Security** section.
```

2021-07-12 16:25 UTC, leslietilling commented on src/stores/admin-signin.md
> +1. Click **Save** the configuration.
```suggestion
1. Click <span class="btn">Save Config</span>.
```

2021-07-15 12:43 UTC, ZhovnirMaria commented on src/stores/admin-signin.md
> +1. Click **Save** the configuration.
Done, thank you🙏😊

2021-07-16 14:19 UTC, leslietilling approved these changes

2021-07-16 14:23 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-16 14:30 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-16 14:55 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-16 16:13 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-21 16:29 UTC, merged