Add the Store Url Options block to the XML Sitemap page
magento/merchdocs pull request #1358
Opened 2021-06-25 09:55 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request adds the Store Url Options block to the XML Sitemap page

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/configuration/catalog/xml-sitemap.html

2021-06-28 12:36 UTC, dobooth requested changes

2021-06-28 12:36 UTC, dobooth commented on src/configuration/catalog/xml-sitemap.md
> +![]({% link images/images/store-url-options.png %}){: .zoom}
Should this image be in this PR?

2021-07-12 16:32 UTC, leslietilling requested changes

2021-07-12 16:32 UTC, leslietilling commented on src/configuration/catalog/xml-sitemap.md
> +|Frequency|Store View|Determines how often store url are updated. Options: Always / Hourly / Daily / Weekly / Monthly / Yearly / Never|
```suggestion
|Frequency|Store View|Determines how often store URLs are updated. Options: Always / Hourly / Daily / Weekly / Monthly / Yearly / Never|
```

2021-07-12 16:32 UTC, leslietilling commented on src/configuration/catalog/xml-sitemap.md
> +|Priority|Store View|A value between 0.0 and 1.0 that determines the priority of store url updates in relation to other content. Zero has the lowest priority.|
```suggestion
|Priority|Store View|A value between 0.0 and 1.0 that determines the priority of store URL updates in relation to other content. Zero (`0.0`) has the lowest priority.|
```

2021-07-15 12:32 UTC, ZhovnirMaria commented on src/configuration/catalog/xml-sitemap.md
> +|Priority|Store View|A value between 0.0 and 1.0 that determines the priority of store url updates in relation to other content. Zero has the lowest priority.|
done, please check<,thanks 🌸

2021-07-16 14:24 UTC, leslietilling approved these changes

2021-07-16 14:29 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-16 15:12 UTC, magento-engcom-team commented
@magento import pr to magento-devdocs/merchdocs

2021-07-16 16:17 UTC, irenelagno commented
@magento import pr to magento-devdocs/merchdocs

2021-07-16 16:18 UTC, magento-engcom-team commented
@irenelagno the pull request successfully imported.

2021-07-21 16:30 UTC, closed without merging