Add description of how to add product attributes to cart price rules
magento/merchdocs pull request #1360
Opened 2021-06-29 09:37 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request adds a description of how to add product attributes to cart price rules

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/price-rules-cart-create.html

2021-07-13 19:53 UTC, leslietilling requested changes
Clarifications and styling edits

2021-07-15 12:27 UTC, ZhovnirMaria commented on src/marketing/price-rules-cart-create.md
> +1. Click **Add** (![Add icon]({% link images/images/btn-add-grn.png %})) and select needed **Product Attribute**.
Done, please check😊

2021-07-16 17:19 UTC, leslietilling approved these changes

2021-07-16 17:47 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-16 19:26 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-16 19:27 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-21 16:29 UTC, merged