Adding a note for content staging preview
magento/merchdocs pull request #1363
Opened 2021-06-30 12:25 UTC by DmitryTsymbal

## Purpose of this pull request

Adding a note that only users with admin permissions can see shared preview

This pull request (PR) ...

## Magento release version

- [ ] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/cms/content-staging-preview.html

- ...
- ...

2021-07-12 17:30 UTC, dobooth commented
Hi @DmitryTsymbal Please look into the linting errors here.

2021-07-13 09:33 UTC, DmitryTsymbal commented
Hi @dobooth , thank you for noticing. I have fixed all errors here

2021-07-13 20:24 UTC, leslietilling requested changes

2021-07-13 20:24 UTC, leslietilling commented on src/cms/content-staging-preview.md
> +     Only Admin users are allowed to see the preview, you are sharing. It is required to create admin account for user before the sharing, if it does not exist.Otherwise, user won’t be able to see a
```suggestion
     An Admin user account is required to see a shared preview. If you have access to [create a new Admin user account]({% link system/permissions-users-all.md %}), you must create the account for a new user before the sharing.
```

2021-07-14 19:45 UTC, leslietilling approved these changes

2021-07-14 19:46 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-21 15:33 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-21 15:34 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-21 18:16 UTC, merged