Describe how to set number of items displayed in the order summary
magento/merchdocs pull request #1364
Opened 2021-06-30 13:31 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request describes how to set number of items displayed in the order summary

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/sales/checkout-process.html

2021-07-14 14:32 UTC, leslietilling requested changes
Edits for clarity and style

2021-07-14 14:32 UTC, leslietilling commented on src/sales/checkout-process.md
> +The admin can change the maximum number of items displayed in the order summary at the checkout it looks neat with fewer products. By default, this value is set to 10.
```suggestion
Admin users can change the maximum number of items displayed in the order summary at checkout to streamline the display with fewer products. By default, this value is set to 10.
```

2021-07-14 14:32 UTC, leslietilling commented on src/sales/checkout-process.md
> +1. Go to **Stores** > **Settings** > **Configuration**.
```suggestion
1. On the _Admin_ sidebar, go to **Stores** > _Settings_ > **Configuration**.
```

2021-07-14 14:32 UTC, leslietilling commented on src/sales/checkout-process.md
> +1. Select **Checkout** under **Sales**.
```suggestion
1. In the left panel, expand **Sales** and choose **Checkout**.
```

2021-07-14 14:32 UTC, leslietilling commented on src/sales/checkout-process.md
> +1. Expand the **Checkout Options** section.
```suggestion
1. Expand ![Expansion selector]({% link images/images/btn-expand.png %}) the **Checkout Options** section.
```

2021-07-14 14:32 UTC, leslietilling commented on src/sales/checkout-process.md
> +1. Change the number in the field **Maximum Number of Items to Display in Order Summary**.
```suggestion
1. For **Maximum Number of Items to Display in Order Summary**, enter the maximum number of items to be displayed.
```

2021-07-14 14:32 UTC, leslietilling commented on src/sales/checkout-process.md
> +1. To save the configuration, click **Save Config**.
```suggestion
1. Click <span class="btn">Save Config</span>.
```

2021-07-14 14:32 UTC, leslietilling commented on src/sales/checkout-process.md
> +   After that, during checkout, only the specified quantity of items is displayed in the order summary:
```suggestion
   With this update, the order summary displayed during checkout is limited to the specified quantity of items.
```

2021-07-15 11:35 UTC, ZhovnirMaria commented on src/sales/checkout-process.md
> +   After that, during checkout, only the specified quantity of items is displayed in the order summary:
Done, please check 🙏

2021-07-15 15:55 UTC, leslietilling approved these changes

2021-07-21 15:34 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-21 15:35 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-21 18:16 UTC, merged