Added explanation for "Applied" option while creating new checkout term and condition
magento/merchdocs pull request #1366
Opened 2021-07-01 11:56 UTC by DmitryTsymbal

## Purpose of this pull request

Added explanation for "Applied" option while creating new checkout term and condition

This pull request (PR) ...

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- ...

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- ...

## Affected documentation pages

https://docs.magento.com/user-guide/sales/terms-and-conditions.html

2021-07-02 10:22 UTC, dmytro-ch requested changes

2021-07-02 10:22 UTC, dmytro-ch commented on src/sales/terms-and-conditions.md
> +   |`Manually`|Customers are required manually accept created condition for placing an order on checkout page.|
```suggestion
   |`Manually`|Customers are required to manually accept the created condition for placing an order on the checkout page.|
```

2021-07-02 10:22 UTC, dmytro-ch commented on src/sales/terms-and-conditions.md
> +   |`Automatically`|Condition will be accepted automatically on checkout.|
```suggestion
   |`Automatically`|Condition will be accepted automatically upon the checkout.|
```

2021-07-14 16:30 UTC, dobooth approved these changes

2021-07-14 16:30 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-07-14 16:31 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-07-16 13:20 UTC, merged