Adding Additional Notes To Email To A Friend Functionality
magento/merchdocs pull request #1367
Opened 2021-07-01 12:48 UTC by DmitryTsymbal

## Purpose of this pull request

Adding Additional Notes To Email To A Friend Functionality for storefront

This pull request (PR) ...

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- ...

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- ...

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/email-a-friend.html

2021-07-02 10:25 UTC, dmytro-ch requested changes

2021-07-02 10:25 UTC, dmytro-ch commented on src/marketing/email-a-friend.md
> +1. On a catalog page, click the **Email** link. Then, if the feature configured only for registered users, do one of the following:
```suggestion
1. On a catalog page, click the **Email** link. Then, if the feature is configured only for registered users, do one of the following:
```

2021-07-02 10:25 UTC, dmytro-ch commented on src/marketing/email-a-friend.md
> +         You can remove added Invitee by clicking the **Remove** link, near **Email** field of needed Invitee.
```suggestion
        You can remove the added Invitee by clicking the **Remove** link, near **Email** field of needed Invitee.
```

2021-07-14 20:15 UTC, leslietilling commented on src/marketing/email-a-friend.md
> +        You can remove the added Invitee by clicking the **Remove** link, near **Email** field of needed Invitee.
```suggestion
        You can remove the added invitee by clicking the **Remove** link.
```

2021-07-14 20:15 UTC, leslietilling approved these changes

2021-07-14 20:18 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-21 15:35 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-21 15:37 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-21 18:16 UTC, merged