Added Information About Deleting Admin Users
magento/merchdocs pull request #1369
Opened 2021-07-02 07:46 UTC by DmitryTsymbal

## Purpose of this pull request

This PR provides an information about deleting admin users

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- ...

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- ...

## Affected documentation pages

https://docs.magento.com/user-guide/system/permissions-users-all.html

2021-07-13 09:05 UTC, DmitryTsymbal commented
@magento run all tests

2021-07-14 20:25 UTC, leslietilling requested changes
Edits for style and clarity

2021-07-14 20:25 UTC, leslietilling commented on src/system/permissions-users-all.md
> +## Deleting Admin Users
```suggestion
## Delete an Admin user
```

2021-07-14 20:25 UTC, leslietilling commented on src/system/permissions-users-all.md
> +1. Navigate to admin users grid: **System** > _Permissions_ > **All Users**.
```suggestion
1. On the _Admin_ sidebar, go to **System** > _Permissions_ > **All Users**.
```

2021-07-14 20:25 UTC, leslietilling commented on src/system/permissions-users-all.md
> +1. Find needed user account using filters on grid and click user name.
```suggestion
1. Locate the user account using filters above the grid and click the user name.
```

2021-07-14 20:25 UTC, leslietilling commented on src/system/permissions-users-all.md
> +1. Enter the current admin' user password into **Your Password** field.
```suggestion
1. When prompted, enter **Your Password** to confirm your identity.
```

2021-07-14 20:25 UTC, leslietilling commented on src/system/permissions-users-all.md
> +1. Confirm the action by clicking <span class="btn">OK</span> button.
```suggestion
1. To confirm the action, click <span class="btn">OK</span>.
```

2021-07-21 15:36 UTC, leslietilling approved these changes

2021-07-21 15:37 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-21 15:38 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-21 18:16 UTC, merged