Added Additional Info About Integration Managing
magento/merchdocs pull request #1370
Opened 2021-07-02 10:08 UTC by DmitryTsymbal

## Purpose of this pull request

Added Additional Info About Integration Managing. Changed outdated screenshot.

This pull request (PR) ...

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- ...

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- ...

## Affected documentation pages

https://docs.magento.com/user-guide/system/integrations.html

2021-07-14 20:42 UTC, leslietilling requested changes
Edits for style and clarity

2021-07-14 20:42 UTC, leslietilling commented on src/system/integrations.md
> +   - Enter the current Admin User password into **Your Password** field.
```suggestion
   - When prompted, enter **Your Password** to confirm your identity.
```

2021-07-14 20:42 UTC, leslietilling commented on src/system/integrations.md
> +## Activating an integration
```suggestion
## Activate an integration
```

2021-07-14 20:42 UTC, leslietilling commented on src/system/integrations.md
> +By default, when the integration was saved, it appears on the grid in _Inactive_ status. To activate it, perform the following steps:
```suggestion
By default, a saved integration appears on the grid with an _Inactive_ status. To activate it, complete the following steps:
```

2021-07-14 20:42 UTC, leslietilling commented on src/system/integrations.md
> +1. Find created integration on grid **System** > _Extensions_ > **Integrations**.
```suggestion
1. On the _Admin_ sidebar, go to **System** > _Extensions_ > **Integrations**.
```

2021-07-14 20:42 UTC, leslietilling commented on src/system/integrations.md
> +1. Click the **Activate** link.
```suggestion
1. Find the newly created integration and click the **Activate** link.
```

2021-07-14 20:42 UTC, leslietilling commented on src/system/integrations.md
> +1. In the upper-right corner click the **Allow** button.
```suggestion
1. In the upper-right corner, click <span class="btn">Allow</span>.
```

2021-07-14 20:42 UTC, leslietilling commented on src/system/integrations.md
> +   Integration Tokens for Extensions will be appeared:
```suggestion
   This displays the Integration Tokens for Extensions. Copy this information to a secure, encrypted location for use with your integration.
```

2021-07-14 20:42 UTC, leslietilling commented on src/system/integrations.md
> +1. In the upper-right corner click the **Done** button.
```suggestion
1. In the upper-right corner, click <span class="btn">Done</span>.
```

2021-07-14 20:42 UTC, leslietilling commented on src/system/integrations.md
> +## Deleting an Integration
```suggestion
## Delete an integration
```

2021-07-14 20:42 UTC, leslietilling commented on src/system/integrations.md
> +1. Find created integration on grid **System** > _Extensions_ > **Integrations**.
```suggestion
1. On the _Admin_ sidebar, go to **System** > _Extensions_ > **Integrations**.
```

2021-07-14 20:42 UTC, leslietilling commented on src/system/integrations.md
> +1. Click the delete icon in **Delete** column
```suggestion
1. Find the existing integration and click the icon ( ![trashcan icon]({% link images/images/btn-trashcan2.png %}) ) in the **Delete** column.
```

2021-07-14 20:42 UTC, leslietilling commented on src/system/integrations.md
> +1. Confirm your action by clicking **OK**
```suggestion
1. To confirm your action, click <span class="btn">OK</span>.
```

2021-07-15 15:41 UTC, leslietilling commented on src/system/integrations.md
> +## Delete an Integration
```suggestion
## Delete an integration
```

2021-07-15 15:44 UTC, leslietilling approved these changes

2021-07-15 15:44 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-15 15:53 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-16 13:20 UTC, merged