Added Information About Deleting Subscribers From Grid
magento/merchdocs pull request #1372
Opened 2021-07-06 08:30 UTC by DmitryTsymbal

## Purpose of this pull request

Added Information About Deleting Subscribers From Grid

This pull request (PR) ...

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- ...

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- ...

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/newsletter-subscribers.html

- ...
- ...

2021-07-21 15:40 UTC, leslietilling requested changes
Just some minor edits for style and consistency

2021-07-21 15:40 UTC, leslietilling commented on src/marketing/newsletter-subscribers.md
> +## Deleting a Subscriber from Newsletter Subscribers list
```suggestion
## Delete a subscriber from the Newsletter Subscribers list
```

2021-07-21 15:40 UTC, leslietilling commented on src/marketing/newsletter-subscribers.md
> +1. Navigate to **Marketing** > _Communications_ > **Newsletter Subscribers**.
```suggestion
1. On the _Admin_ sidebar, go to **Marketing** > _Communications_ > **Newsletter Subscribers**.
```

2021-07-30 14:51 UTC, leslietilling approved these changes

2021-07-30 15:03 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-30 15:04 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-30 16:34 UTC, merged