Added Additional Information About Wish Lists Managing
magento/merchdocs pull request #1378
Opened 2021-07-08 08:28 UTC by DmitryTsymbal

## Purpose of this pull request

Added Additional Information About Wish Lists Managing:

- Move items to a different list
- Copy items to a different list
- Delete Created Wish Lists

This pull request (PR) ...

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- ...

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- ...

## Affected documentation pages

https://docs.magento.com/user-guide/customers/account-dashboard-my-wish-list.html

- ...
- ...

2021-07-21 15:54 UTC, leslietilling requested changes
For the user guide, the "you" is the merchant who uses the Admin and configures storefront functionality. For procedures that are done by customers on the storefront, we should be writing as third person. There are still many existing items that ned to be corrected, but as we add or edit we are trying to make this changeover.

2021-07-21 15:54 UTC, leslietilling commented on src/customers/account-dashboard-my-wish-list.md
> +1. Select the checkbox of each item to be moved.
```suggestion
1. Customer selects the checkbox of each item to be moved.
```

2021-07-21 15:54 UTC, leslietilling commented on src/customers/account-dashboard-my-wish-list.md
> +1. Click **Move Selected to Wish List** and do one of the following:
```suggestion
1. Clicks **Move Selected to Wish List** and does one of the following:
```

2021-07-21 15:54 UTC, leslietilling commented on src/customers/account-dashboard-my-wish-list.md
> +    - Click **Create New Wish List**.
```suggestion
    - Chooses an existing wish list.
    - Clicks **Create New Wish List**.
```

2021-07-21 15:54 UTC, leslietilling commented on src/customers/account-dashboard-my-wish-list.md
> +1. Select the checkbox of each item to be moved.
```suggestion
1. Selects the checkbox of each item to be moved.
```

2021-07-21 15:54 UTC, leslietilling commented on src/customers/account-dashboard-my-wish-list.md
> +1. Click **Copy Selected to Wish List** and do one of the following:
```suggestion
1. Clicks **Copy Selected to Wish List** and does one of the following:
```

2021-07-21 15:54 UTC, leslietilling commented on src/customers/account-dashboard-my-wish-list.md
> +    - Click **Create New Wish List**.
```suggestion
    - Chooses an existing wish list.
    - Clicks **Create New Wish List**.
```

2021-07-21 15:54 UTC, leslietilling commented on src/customers/account-dashboard-my-wish-list.md
> +## Delete Created Wish Lists
```suggestion
## Delete an existing wish list
```

2021-07-21 15:54 UTC, leslietilling commented on src/customers/account-dashboard-my-wish-list.md
> +1. Open the wish list to be deleted.
```suggestion
1. Customer opens the wish list to be deleted.
```

2021-07-21 15:54 UTC, leslietilling commented on src/customers/account-dashboard-my-wish-list.md
> +1. Click the **Delete Wish List** button.
```suggestion
1. Clicks <span class="btn">Delete Wish List</span>.
```

2021-07-21 15:54 UTC, leslietilling commented on src/customers/account-dashboard-my-wish-list.md
> +1. When prompted to confirm, click <span class="btn">OK</span> button.
```suggestion
1. When prompted to confirm, clicks <span class="btn">OK</span>.
```

2021-07-30 15:05 UTC, leslietilling commented on src/customers/account-dashboard-my-wish-list.md
> +## Delete Created Wish Lists
```suggestion
## Delete created wish lists
```

2021-07-30 15:06 UTC, leslietilling approved these changes

2021-07-30 15:07 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-30 15:08 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-30 16:34 UTC, merged