Added additional information about user roles managing
magento/merchdocs pull request #1393
Opened 2021-07-16 08:47 UTC by DmitryTsymbal

## Purpose of this pull request

_Added additional information about user roles managing. Editing/Deleting Roles._

This pull request (PR) ...

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- ...

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- ...

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/system/permissions-user-roles.html/>._

2021-07-21 16:43 UTC, leslietilling requested changes
Just a minor addition to clarify "changes".

2021-07-21 16:43 UTC, leslietilling commented on src/system/permissions-user-roles.md
> +1. Make needed changes.
```suggestion
1. Make needed changes.
```
```suggestion
1. Make needed changes.

   Review the steps for creating a user role for information. about the role settings.
```

2021-07-30 15:11 UTC, leslietilling approved these changes

2021-07-30 15:13 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-30 15:14 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-30 16:34 UTC, merged