Add information about RMA shipping methods
magento/merchdocs pull request #1397
Opened 2021-07-19 12:52 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request:
- adds information about RMA shipping methods;
- adds commerce label to the Autosetting page

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- yes

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/sales/rma-configure.html
https://docs.magento.com/user-guide/catalog/product-autosettings.html?itm_source=merchdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=auto

2021-07-21 17:02 UTC, leslietilling requested changes
Minor edits for clarity and consistency

2021-07-21 17:02 UTC, leslietilling commented on src/catalog/product-autosettings.md
> +With RMA, the admin has the ability to allow return functionality for specific products, and vice versa could also disallow the returning of specific products.
```suggestion
With RMA, the an Admin user has the ability to allow return functionality for specific products, as well as disallow the returning of specific products.
```

2021-07-23 11:44 UTC, ZhovnirMaria commented on src/catalog/product-autosettings.md
> +With RMA, the admin has the ability to allow return functionality for specific products, and vice versa could also disallow the returning of specific products.
Done, thanks 🙏

2021-07-23 14:15 UTC, leslietilling approved these changes

2021-07-23 14:16 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-23 14:17 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-23 15:49 UTC, merged