Describe the returns attributes creation process
magento/merchdocs pull request #1412
Opened 2021-07-26 12:34 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request describes the returns attributes creation process. 
This block was described due to the fact that it is partially different from creating custom attributes.

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- yes

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- yes

## Affected documentation pages

https://docs.magento.com/user-guide/stores/attributes-returns.html?itm_source=merchdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=Returns%20Attributes

2021-07-26 15:30 UTC, leslietilling requested changes
Minor edits

2021-07-26 15:30 UTC, leslietilling commented on src/stores/attributes-returns.md
> +1. To limit the size of Text Field and Text Area input types, enter the **Minimum Text Length** and **Maximum Text Length**.
```suggestion
1. For the Text Field and Text Area input types, enter the **Minimum Text Length** and **Maximum Text Length**.
```

2021-07-26 15:30 UTC, leslietilling commented on src/stores/attributes-returns.md
> +1. To apply a preprocessing filter set Input/Output Filter to one of the following:
```suggestion
1. To apply a preprocessing filter, set **Input/Output Filter** to one of the following:
```

2021-07-26 15:30 UTC, leslietilling commented on src/stores/attributes-returns.md
> +1. In the left panel, choose Manage Labels/Options.
```suggestion
1. In the left panel, choose **Manage Labels/Options**.
```

2021-07-28 14:22 UTC, leslietilling approved these changes

2021-07-28 15:09 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-28 18:29 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-07-28 18:30 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-07-30 16:34 UTC, merged