MC-42708: Scheduled Export does not triggered by cron
magento/merchdocs pull request #1418
Opened 2021-07-28 18:01 UTC by thiaramus

## Purpose of this pull request

This pull request (PR) is to add a callout stressing that after saving a scheduled import or export, there is a cache invalidation banner appearing at the top of the admin area. If the instructions from the banner will not be followed, the scheduled update won't take effect until the cache is flushed.

## Magento release version

 - 2.3
 - 2.4
## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- This update is specific to Adobe Commerce only

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- EE

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/system/data-schedule-export.html
- https://docs.magento.com/user-guide/system/data-schedule-import.html
- https://docs.magento.com/user-guide/system/data-scheduled-import-export.html

2021-07-29 22:44 UTC, leslietilling requested changes
Minor edits for clarity and newer brand language

2021-07-29 22:44 UTC, leslietilling commented on src/system/data-schedule-export.md
> +Scheduled export makes changes to Magento system configuration. After saving, make sure you follow the cache invalidation notice that will appear on top of the Magento admin page and flush the cache
```suggestion
Scheduled export makes changes to the system configuration. After saving, make sure you address the cache invalidation notice that appears at the top of the Admin page and flush the cache in order to apply the new or updated schedule.
```

2021-07-29 22:44 UTC, leslietilling commented on src/system/data-schedule-import.md
> +Scheduled import makes changes to Magento system configuration. After saving, make sure you follow the cache invalidation notice that will appear on top of the Magento admin page and flush the cache
```suggestion
Scheduled import makes changes to the system configuration. After saving, make sure you address the cache invalidation notice that appears at the top of the Admin page and flush the cache in order to apply the new or updated schedule.
```

2021-07-29 22:44 UTC, leslietilling commented on src/system/data-scheduled-import-export.md
> +   Scheduled import/export makes changes to Magento system configuration. After saving, make sure you follow the cache invalidation notice that will appear on top of the Magento admin page and flush
```suggestion
   Scheduled import/export makes changes to the system configuration. After saving, make sure you address the cache invalidation notice that appears at the top of the Admin page and flush the cache in order to apply the new or updated schedule.
```

2021-07-30 12:39 UTC, thiaramus commented
Thanks @leslietilling, I committed the requested corerections.

2021-07-30 14:12 UTC, leslietilling approved these changes

2021-07-30 14:16 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-30 14:48 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-07-30 14:49 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-07-30 16:34 UTC, merged