Added the point about deleting permission rules for categories
magento/merchdocs pull request #1428
Opened 2021-08-10 09:52 UTC by DmitryTsymbal

## Purpose of this pull request

Added the point about deleting permission rules for categories

## Affected documentation pages

https://docs.magento.com/user-guide/catalog/catalog-shared-category-permissions-update.html

2021-08-16 15:54 UTC, leslietilling requested changes
minor edit

2021-08-16 15:54 UTC, leslietilling commented on src/catalog/catalog-shared-category-permissions-update.md
> +    - To delete permission rule, click the ![]({% link images/images/btn-trashcan2.png %}) icon.
```suggestion
    - To delete a permission rule, click the ![Trash can]({% link images/images/btn-trashcan2.png %}) icon.
```

2021-08-18 19:28 UTC, leslietilling approved these changes

2021-08-18 19:28 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-19 14:53 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-19 14:54 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-08-24 14:00 UTC, merged