New topic about how to Add GTM (Google Tag Manager) For Magento 2 Stores
magento/merchdocs pull request #1431
Opened 2021-08-11 13:29 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) adds new topic about how to Add GTM (Google Tag Manager) For Magento 2 Stores

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- Adobe Commerce 

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- ...

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/marketing/google-tag-manager-create-tag.html

## Links to Magento source code or PRs

_OPTIONAL. If this pull request references a file in a Magento codebase repository or a code PR, add it here._

- https://developers.google.com/tag-manager/devguide

2021-08-16 16:03 UTC, leslietilling commented
@EvheniiaKolkhiieva  Seems like this should be a "Step 4" for this topic rather than a new topic?: https://docs.magento.com/user-guide/marketing/google-tag-manager.html  

We don't want to create many small topics. We will be removing the Troubleshooting topic in that section.

2021-08-17 13:32 UTC, EvheniiaKolkhiieva commented
Hi @leslietilling , I have added "Step 4" for this topic -  https://docs.magento.com/user-guide/marketing/google-tag-manager.html, and delete previous changes. I can also remove the Troubleshooting topic in that section as part of this PR, what do you think?

2021-08-19 15:25 UTC, leslietilling requested changes
Edits for style, clarity, and branding

2021-08-19 15:25 UTC, leslietilling commented on src/marketing/google-tag-manager.md
> +1. When complete, click <span class="btn">Save Configuratio</span>.
```suggestion
## Step 4. Add the GTM code to your Adobe Commerce store

1. Copy the GTM code:

   There are two GTM code snippets to be added to your Commerce site: the first one for the <head> tag and the and the second for the <body> tag.

    ![Install Google Tag Manager]({% link images/images-ee/install-google-tag-manager.png %}){: .zoom}
    _Google Tag Manager code_

1. In the Commerce Admin, go to **Content** > _Design_ > **Configuration** and open the store view in edit mode.

1. Under _Other Settings_, expand **HTML Head** and paste the code you copied from GTM for the <head> tag in the **Scripts and Style Sheets** field.

    ![Install Google Tag Manager]({% link images/images-ee/head-tag.png %}){: .zoom}
    _Inserting code in the HTML Head_

1. Expand **Footer** and paste the GTM code for <body> in the **Miscellaneous HTML** field.

    ![Install Google Tag Manager]({% link images/images-ee/footer-tag-section.png %}){: .zoom}
    _Inserting code in the Footer_

1. When complete, click <span class="btn">Save Configuration</span>.
```

2021-08-22 17:36 UTC, EvheniiaKolkhiieva commented
Hi @leslietilling , thank you!
I'm done, please check and approve this PR 😊☀️

2021-08-22 17:37 UTC, EvheniiaKolkhiieva commented on src/marketing/google-tag-manager.md
> +1. When complete, click <span class="btn">Save Configuratio</span>.
Done ✅

2021-08-23 15:03 UTC, leslietilling approved these changes

2021-08-23 15:04 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-23 15:18 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-23 15:19 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-08-24 14:00 UTC, merged