Add description about steps to translate product attribute and attribute options in Magento 2
magento/merchdocs pull request #1433
Opened 2021-08-11 14:51 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) adds description about steps to translate product attribute and attribute options in Magento 2

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/catalog/product-translate.html

whatsnew
Updated the [Translating Products](https://docs.magento.com/user-guide/catalog/product-translate.html) topic to include steps for translating product attributes and attribute options.

2021-08-16 16:17 UTC, leslietilling requested changes
Minor edits for style and clarity

2021-08-16 16:17 UTC, leslietilling commented on src/catalog/product-translate.md
> +1. Navigate to _Stores > Attributes > Product_ and select the attribute to be translated.
```suggestion
1. On. the _Admin_ sidebar, go to **Stores** > _Attributes_ > **Product**.

1. Select the attribute to be translated.
```

2021-08-16 16:17 UTC, leslietilling commented on src/catalog/product-translate.md
> +1. Under the **Manage Label** section, set the translated attribute title.
```suggestion
1. Choose **Manage Label** on the left and set the **Managed Titles** options to define the attribute title translations.
```

2021-08-16 16:17 UTC, leslietilling commented on src/catalog/product-translate.md
> +    _Manage Label tab_
```suggestion
    _Manage Titles_
```

2021-08-16 16:17 UTC, leslietilling commented on src/catalog/product-translate.md
> +1. Under _Properties > Manage Options (Values of Your Attribute)_, translate the attribute options
```suggestion
1. Choose **Properties** on the left and enter the translated attribute options in the **Manage Options** section.
```

2021-08-16 16:17 UTC, leslietilling commented on src/catalog/product-translate.md
> +    _Manage Option tab_
```suggestion
    _Manage Options_
```

2021-08-17 12:44 UTC, EvheniiaKolkhiieva commented
Hi @leslietilling , thank you for the rewiew. I have implemented your suggestions, please approve the PR. Thank you! 😊

2021-08-17 12:44 UTC, EvheniiaKolkhiieva commented on src/catalog/product-translate.md
> +    _Manage Option tab_
Done ✅

2021-08-17 12:44 UTC, EvheniiaKolkhiieva commented on src/catalog/product-translate.md
> +1. Under _Properties > Manage Options (Values of Your Attribute)_, translate the attribute options
Done ✅

2021-08-17 12:44 UTC, EvheniiaKolkhiieva commented on src/catalog/product-translate.md
> +    _Manage Label tab_
Done ✅

2021-08-17 12:44 UTC, EvheniiaKolkhiieva commented on src/catalog/product-translate.md
> +1. Under the **Manage Label** section, set the translated attribute title.
Done ✅

2021-08-17 12:44 UTC, EvheniiaKolkhiieva commented on src/catalog/product-translate.md
> +1. Navigate to _Stores > Attributes > Product_ and select the attribute to be translated.
Done ✅

2021-08-19 15:27 UTC, leslietilling commented on src/catalog/product-translate.md
> +1. On. the _Admin_ sidebar, go to **Stores** > _Attributes_ > **Product**.
This was my typo in comments
```suggestion
1. On the _Admin_ sidebar, go to **Stores** > _Attributes_ > **Product**.
```

2021-08-19 15:28 UTC, leslietilling approved these changes

2021-08-19 15:44 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-19 16:02 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-19 16:03 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-08-24 14:00 UTC, merged