Added additional info about blocks managing
magento/merchdocs pull request #1436
Opened 2021-08-17 09:22 UTC by DmitryTsymbal

## Purpose of this pull request

Added additional info about blocks managing
Deleted non-existent button "Save&New"

## Affected documentation pages

https://docs.magento.com/user-guide/cms/block-add.html

2021-08-19 16:56 UTC, leslietilling requested changes
Just some minor edits for style and clarity

2021-08-19 16:56 UTC, leslietilling commented on src/cms/block-add.md
> +## Delete a block
```suggestion
## Delete a block

```

2021-08-19 16:56 UTC, leslietilling commented on src/cms/block-add.md
> +There are two ways to remove created block. You can remove it from Blocks grid, or from the edit block page.
```suggestion
There are two ways to remove created block. You can remove it from _Blocks_ grid, or from the edit block page.
```

2021-08-19 16:56 UTC, leslietilling commented on src/cms/block-add.md
> +1. Locate the blocks using filters above the grid, select the checkbox of the blocks to be deleted.
```suggestion
1. Locate the blocks using filters above the grid and select the checkbox for one or more blocks to be deleted.
```

2021-08-19 16:56 UTC, leslietilling commented on src/cms/block-add.md
> +1. In the **Actions** column choose `Edit`.
```suggestion
1. In the _Actions_ column for the block, click **Select** and choose **Edit**.
```

2021-08-23 15:52 UTC, leslietilling approved these changes

2021-08-23 16:43 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-23 16:50 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-23 16:51 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-08-24 14:00 UTC, merged