Added Additional Info About Billing Agreements
magento/merchdocs pull request #1437
Opened 2021-08-18 09:58 UTC by DmitryTsymbal

## Purpose of this pull request

Added Additional Info About Billing Agreements

## Affected documentation pages

https://docs.magento.com/user-guide/sales/billing-agreements.html

2021-08-19 17:17 UTC, leslietilling requested changes
Edits for style and clarity

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +### Grid Column descriptions
```suggestion
## Column descriptions
```

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +1. Click the needed billing agreement to be viewed.
```suggestion
1. Find the billing agreement in the list and click to open it.
```

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +1. In the right upper corner click the **Delete** button.
```suggestion
1. In the top-right corner, click **Delete**.
```

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +1. To confirm the action click **OK**.
```suggestion
1. To confirm the action, click **OK**.
```

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +1. Click the needed billing agreement to be viewed.
```suggestion
1. Find the billing agreement in the list and click to open it.
```

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +## Delete the Billing Agreement
```suggestion
## Delete the billing agreement
```

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +## Cancel the Billing Agreement
```suggestion
## Cancel the billing agreement
```

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +1. In the right upper corner click the **Cancel** button.
```suggestion
1. In the top-right corner, click **Cancel**.
```

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +1. To confirm the action click **OK**.
```suggestion
1. To confirm the action, click **OK**.
```

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +Contains the list of the orders placed using current Billing Agreement
```suggestion
This tab displays the list of the orders placed using the current billing agreement.
```

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +Each Billing Agreement page consist of two tabs: **General Information** and **Related Orders**.
```suggestion
Each billing agreement page consists of two tabs: _General Information_ and _Related Orders_.
```

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +Contains general information about billing agreement:
```suggestion
This tab includes the general information about the billing agreement:
```

2021-08-19 17:17 UTC, leslietilling commented on src/sales/billing-agreements.md
> +1. Click the needed billing agreement to be viewed.
Combine these steps to one like the other following procedures:

`1. Find the billing agreement in the list and click to open it.`

2021-08-23 17:29 UTC, leslietilling approved these changes

2021-08-23 17:29 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-23 17:32 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-23 17:33 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-08-24 14:00 UTC, merged