Add steps about how to Remove Filterable Attribute Values with 0 Products from Layered Navigation
magento/merchdocs pull request #1438
Opened 2021-08-18 10:53 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) adds steps about how to Remove Filterable Attribute Values with 0 Products from Layered Navigation

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/catalog/navigation-layered-filterable-attributes.html

2021-08-19 17:26 UTC, leslietilling requested changes
Edits for style and clarity

2021-08-19 17:26 UTC, leslietilling commented on src/catalog/navigation-layered-filterable-attributes.md
> +## Remove Filterable Attribute Values with 0 Products from Layered Navigation
```suggestion
## Remove filterable attribute values from layered navigation
```

2021-08-19 17:26 UTC, leslietilling commented on src/catalog/navigation-layered-filterable-attributes.md
> +Layered navigation includes filters for all available attribute values and their product counts, including those with zero (0) product matches as shown in below image:
```suggestion
Layered navigation includes filters for all available attribute values and their product counts, including those with zero (0) product matches (as shown in the following image).
```

2021-08-19 17:26 UTC, leslietilling commented on src/catalog/navigation-layered-filterable-attributes.md
> +Therefore, follow the next steps to remove Filterable Attribute Values with 0 Products from Layered Navigation:
```suggestion
You can use the following steps to remove filterable attribute values with 0 Products from the layered navigation:
```

2021-08-19 17:26 UTC, leslietilling commented on src/catalog/navigation-layered-filterable-attributes.md
> +1. On the _Admin_ sidebar, go to **Stores** > **Attributes** > **Product**.
```suggestion
1. On the _Admin_ sidebar, go to **Stores** > _Attributes_ > **Product**.
```

2021-08-19 17:26 UTC, leslietilling commented on src/catalog/navigation-layered-filterable-attributes.md
> +1. Click on **Storefront Properties** under **Attribute Information** section.
```suggestion
1. Under _Attribute Information_ , click **Storefront Properties**.
```

2021-08-19 17:26 UTC, leslietilling commented on src/catalog/navigation-layered-filterable-attributes.md
> +1. Select **Filterable (with results)** from the Use in Layered Navigation dropdown.
```suggestion
1. For **Layered Navigation**, choose `Filterable (with results)`.
```

2021-08-20 06:42 UTC, EvheniiaKolkhiieva commented
Hi @leslietilling , thank you for your review. I Have implemented your suggestions , please approve this PR ☀️
Thank you!

2021-08-20 06:42 UTC, EvheniiaKolkhiieva commented on src/catalog/navigation-layered-filterable-attributes.md
> +1. Select **Filterable (with results)** from the Use in Layered Navigation dropdown.
Done ✅

2021-08-20 06:42 UTC, EvheniiaKolkhiieva commented on src/catalog/navigation-layered-filterable-attributes.md
> +1. Click on **Storefront Properties** under **Attribute Information** section.
Done ✅

2021-08-20 06:42 UTC, EvheniiaKolkhiieva commented on src/catalog/navigation-layered-filterable-attributes.md
> +1. On the _Admin_ sidebar, go to **Stores** > **Attributes** > **Product**.
Done ✅

2021-08-20 06:42 UTC, EvheniiaKolkhiieva commented on src/catalog/navigation-layered-filterable-attributes.md
> +Therefore, follow the next steps to remove Filterable Attribute Values with 0 Products from Layered Navigation:
Done ✅

2021-08-20 06:43 UTC, EvheniiaKolkhiieva commented on src/catalog/navigation-layered-filterable-attributes.md
> +Layered navigation includes filters for all available attribute values and their product counts, including those with zero (0) product matches as shown in below image:
Done ✅

2021-08-20 06:43 UTC, EvheniiaKolkhiieva commented on src/catalog/navigation-layered-filterable-attributes.md
> +## Remove Filterable Attribute Values with 0 Products from Layered Navigation
Done ✅

2021-08-20 14:26 UTC, leslietilling commented on src/catalog/navigation-layered-filterable-attributes.md
> + Under _Attribute Information_ , click **Storefront Properties**.
one more fix, I'll commit
```suggestion
 1. Under _Attribute Information_ , click **Storefront Properties**.
```

2021-08-20 14:27 UTC, leslietilling approved these changes

2021-08-20 14:34 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-20 14:53 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-20 14:54 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-08-24 14:00 UTC, merged