Transactions: Fixed the broken link, added additional info
magento/merchdocs pull request #1439
Opened 2021-08-18 11:28 UTC by DmitryTsymbal

## Purpose of this pull request

Fixed the broken link to orders page
Added additional info about fetching transaction details

## Affected documentation pages

https://docs.magento.com/user-guide/sales/transactions.html

2021-08-19 17:28 UTC, leslietilling requested changes
Thanks for fix. Just one minor edit for note.

2021-08-19 17:28 UTC, leslietilling commented on src/sales/transactions.md
> +If the transaction details are not available or outdated click the **Fetch** button in menu bar to update them.
```suggestion
If the transaction details are not available or are outdated, click **Fetch** in the button bar to update them.
```

2021-08-23 17:59 UTC, leslietilling approved these changes

2021-08-23 18:00 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-24 14:37 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-24 14:38 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-08-24 19:42 UTC, merged