Added additional information to search report page
magento/merchdocs pull request #1440
Opened 2021-08-18 13:11 UTC by DmitryTsymbal

## Purpose of this pull request

Added additional information to search report page

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/search-terms-report.html

2021-08-19 19:27 UTC, leslietilling requested changes
Edits for style and clarity

2021-08-19 19:27 UTC, leslietilling commented on src/marketing/search-terms-report.md
> +|Hits|Number of Uses|
```suggestion
## Export the Search Terms report

1. For **Export to**, choose an export format:

    - **CSV** - A comma-separated value file containing plain text data
    - **Excel XML** - An XML-based, spreadsheet data format

1. Click <span class="btn">Export</span>.

The generated file is automatically saved to your designated folder for downloads.

## Column descriptions

|Column|Description|
|--- |--- |
|ID|Unique, numeric ID generated for the search term entry|
|Search Query|The query used to perform the search|
|Store|The store where the search query was applied|
|Results|Number of results|
|Hits|Number of uses|
```

2021-08-24 14:38 UTC, leslietilling approved these changes

2021-08-24 14:39 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-24 14:40 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-08-24 19:42 UTC, merged