Add clarification how to set up comments for shipment
magento/merchdocs pull request #1442
Opened 2021-08-18 17:21 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) adds clarification how to set up comments for shipment

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/sales/order-ship.html

2021-08-20 23:33 UTC, leslietilling requested changes

2021-08-20 23:33 UTC, leslietilling commented on src/sales/shipments-create.md
> +- Send **Shipment Comment Email Copy Method**, select bcc(blind carbon copy) or separate email copy method based on your requirement.
```suggestion
1. Expand the **Shipment Comments** section and modify the settings as needed:

   - The **Enabled** option is set to `Yes` by default, which means that the email is sent to a customer when a shipping comment is entered.

   - For **Shipment Comment Email Sender**, select the person from whom the shipment comment email is sent. The default offers five email addresses.

   - For **Shipment Comment Email Template**, select the template based on your requirement or select the default option.

   - For **Shipment Comment Email Template for Guests**, choose the template used for customers who do not have an account in your store.

   - For **Shipment Comment Email Copy To**, enter the email addresses to send a shipment comment email copy. Separate multiple email addresses with a comma.

   - For **Shipment Comment Email Copy Method**, select `bcc` (blind carbon copy) or `separate email copy` method based on your preference.
```

2021-08-20 23:33 UTC, leslietilling commented on src/sales/shipments-create.md
> +    _Shipment Coment Configuration_
```suggestion
    _Shipment comment configuration_
```

2021-08-22 17:56 UTC, EvheniiaKolkhiieva commented
Hi @leslietilling , thank you for the review. I have implemented your suggestions, could you please approve this PR?
Thank you!

2021-08-22 17:56 UTC, EvheniiaKolkhiieva commented on src/sales/shipments-create.md
> +    _Shipment Coment Configuration_
Done ✅

2021-08-22 17:56 UTC, EvheniiaKolkhiieva commented on src/sales/shipments-create.md
> +- Send **Shipment Comment Email Copy Method**, select bcc(blind carbon copy) or separate email copy method based on your requirement.
Done ✅

2021-08-22 17:56 UTC, EvheniiaKolkhiieva commented on src/sales/shipments-create.md
> +1. On the _Admin_ sidebar, go to **Stores** > **Settings** > **Configuration**.
Done ✅

2021-08-22 17:56 UTC, EvheniiaKolkhiieva commented on src/sales/shipments-create.md
> +### To set up comments for shipment do the following:
Done ✅

2021-08-23 15:10 UTC, leslietilling approved these changes

2021-08-23 15:55 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-24 14:40 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-08-24 14:41 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-08-24 19:42 UTC, merged