Describe payment gateway method for the stores
magento/merchdocs pull request #1448
Opened 2021-08-19 09:51 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request describes payment gateway method for the stores

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/payment/paypal.html?itm_source=merchdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=Payment%20Gateway

2021-08-19 19:18 UTC, shrielenee requested changes

2021-08-19 19:18 UTC, shrielenee commented on src/payment/paypal.md
> +A payment gateway is an intermediary between customer and bank, it's an electronic payment service that authorizes credit and debit card transactions. Payment gateways are available in online and off
```suggestion
A payment gateway is a merchant service provided by an e-commerce application service provider that authorizes credit card or direct payments processing. They work as intermediaries between customers and banks.

Payment gateways are available in online and offline environments. Payments can be accepted by phone, online, or through a mobile app. The transaction is sent to the service provider's processing system and then sent to the customer's bank for verification and confirmation. If verified, the merchant receives the payment without having direct contact with the customer's bank account.
```

2021-08-19 19:18 UTC, shrielenee commented on src/payment/paypal.md
> +There are two types of payment gateways - direct and hosted.
```suggestion
There are two types of payment gateways---direct and hosted.
```

2021-08-19 19:18 UTC, shrielenee commented on src/payment/paypal.md
> +- Direct payment gateway allows users to enter their card details in the store itself.
```suggestion
- Direct payment gateways allow users to enter their card details on the store website.
```

2021-08-19 19:18 UTC, shrielenee commented on src/payment/paypal.md
> +- Hosted payment gateway redirects user to hosted payment page.
```suggestion
- Hosted payment gateways redirect users to a hosted payment page, outside of the store website.
```

2021-08-24 17:56 UTC, shrielenee approved these changes

2021-08-24 18:57 UTC, dobooth commented
@magento import code to magento-devdocs/merchdocs

2021-08-24 18:58 UTC, magento-engcom-team commented
@dobooth the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1448`.

2021-08-24 19:42 UTC, merged