Update image and add description for "Allow remote shopping assistance" and "Show Password"
magento/merchdocs pull request #1468
Opened 2021-08-31 04:22 UTC by pawan

## Purpose of this pull request

Fix for #1449 

## Magento release version

2.4

## Product editions

Magento Open Source 
Adobe Commerce

## Affected documentation pages

https://docs.magento.com/user-guide/customers/account-create.html

2021-09-01 20:45 UTC, leslietilling approved these changes

2021-09-01 20:45 UTC, leslietilling commented on src/customers/account-create.md
> +1. If you want to allows merchants to [See what you see]({% link customers/login-as-customer.md %}) and take actions on your behalf in order to provide better assistance, select the **Allow remote sh
```suggestion
1. If you want to enable store support staff to [see what you see]({% link customers/login-as-customer.md %}) and take actions on your behalf in order to provide better assistance, select the **Allow remote shopping assistance** checkbox.
```

2021-09-01 20:45 UTC, leslietilling commented on src/customers/account-create.md
> +1. Click <span class="btn">Show Password</span> to see what password you are entering.
```suggestion
1. If needed, click <span class="btn">Show Password</span> to see view the password you entered.
```

2021-09-01 20:46 UTC, leslietilling requested changes
Just a couple of edits

2021-09-02 02:15 UTC, pawan commented
> Just a couple of edits

Updated @leslietilling

2021-09-02 14:55 UTC, leslietilling approved these changes

2021-09-02 14:59 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-08 15:15 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-08 15:37 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-08 15:38 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-09-09 16:13 UTC, merged