Describe how to manage the sales reports
magento/merchdocs pull request #1469
Opened 2021-08-31 14:22 UTC by ZhovnirMaria

## Purpose of this pull request

This pull request describes how to manage the sales reports

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/reports/sales-reports.html

2021-09-01 20:49 UTC, leslietilling requested changes

2021-09-01 20:49 UTC, leslietilling commented on src/reports/sales-reports.md
> +1. To update statistics, click on the anchor text `here`.
```suggestion
1. To update statistics, click **here** in the text.
```

2021-09-01 20:49 UTC, leslietilling commented on src/reports/sales-reports.md
> +Admin can get a whole website or one store report, a report for a time interval or a date. To filter sale report set:
```suggestion
In the Admin, you can access can generate a report for a whole website or for one store, within a time interval or a date. To filter a sale report, set the following options:
```

2021-09-10 15:10 UTC, leslietilling approved these changes

2021-09-10 15:10 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-10 15:18 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-10 15:24 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-10 15:25 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-09-13 17:09 UTC, merged