Added additional information to event-update page
magento/merchdocs pull request #1475
Opened 2021-09-01 13:25 UTC by DmitryTsymbal

## Purpose of this pull request

Added additional information about how to delete an event and buttons bar.
Replaced the screenshot with new more accurate. Previous screenshot contained an information from creating new event entry instead of update existing event entry

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/event-update.html

2021-09-02 17:11 UTC, BarnyShergold requested changes
Just a few minor corrections.

2021-09-02 17:11 UTC, BarnyShergold commented on src/marketing/event-update.md
> +1. Find the event in the list, and open it in edit mode.
```suggestion
1. Find the event in the list and open it in edit mode.
```

2021-09-02 17:11 UTC, BarnyShergold commented on src/marketing/event-update.md
> +|<span class="btn">Back</span>|Returns to the Events page without saving the new event or changes in existing.|
```suggestion
|<span class="btn">Back</span>|Returns to the Events page without saving the new event or changes in an existing event.|
```

2021-09-02 17:11 UTC, BarnyShergold commented on src/marketing/event-update.md
> +|<span class="btn">Reset</span>|Clears the form of any unsaved changes, and restores the original event information.|
```suggestion
|<span class="btn">Reset</span>|Clears the form of any unsaved changes and restores the original event information.|
```

2021-09-06 13:54 UTC, DmitryTsymbal commented on src/marketing/event-update.md
> +|<span class="btn">Save and Continue Edit</span>|Saves all changes, and keeps the form open in edit mode.|
Thanks for the review! Changes applied.

2021-09-07 08:48 UTC, BarnyShergold approved these changes
Thanks!

2021-09-08 15:26 UTC, leslietilling approved these changes

2021-09-08 15:53 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-08 15:54 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-09-09 16:13 UTC, merged