Fix markdown in the Workspace controls sheet
magento/merchdocs pull request #1476
Opened 2021-09-01 13:33 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) fixes markdown in the Workspace controls sheet
![image](https://user-images.githubusercontent.com/78729171/131680579-efe107cc-c15a-4c11-a854-f7f3bff0730b.png)

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/catalog/products.html

2021-09-02 17:06 UTC, BarnyShergold requested changes

2021-09-02 17:06 UTC, BarnyShergold commented on src/catalog/products.md
> +|Add Product|Initiates the process to create a new simple product. To choose a specific product type, click the down arrow. Options: [Simple Product]({% link catalog/product-create-simple.md %}) / [C
I think the closing tag also needs removing.
```suggestion
|Add Product|Initiates the process to create a new simple product. To choose a specific product type, click the down arrow. Options: [Simple Product]({% link catalog/product-create-simple.md %}) / [Configurable Product]({% link catalog/product-create-configurable.md %}) / [Grouped Product]({% link catalog/product-create-grouped.md %}) / [Virtual Product]({% link catalog/product-create-virtual.md %}) / [Bundle Product]({% link catalog/product-create-bundle.md %}) / [Downloadable Product]({% link catalog/product-create-downloadable.md %}) / [Gift Card]({% link catalog/product-gift-card.md %})|
```

2021-09-03 15:28 UTC, EvheniiaKolkhiieva commented
Hi @BarnyShergold , thank you for reviewing. I have implemented your suggestion, could you please approve this PR?
Thank you!

2021-09-03 15:49 UTC, BarnyShergold approved these changes
Nice! BTW if you agree a change that's simple it's easier to PR again if you accept the suggestion on here rather than making the changes locally and re-pushing.

2021-09-03 15:53 UTC, EvheniiaKolkhiieva commented
Oh @BarnyShergold  what a good observation! I never tried to do that, thank you, I will definitely try 😊

2021-09-08 13:42 UTC, dobooth approved these changes

2021-09-08 13:42 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-09-08 13:43 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-09-09 16:13 UTC, merged