Added additional information to RMA process from customer's account
magento/merchdocs pull request #1485
Opened 2021-09-03 12:53 UTC by DmitryTsymbal

## Purpose of this pull request

Added additional information to RMA process from customer's account

## Affected documentation pages

https://docs.magento.com/user-guide/sales/rma-customer-experience.html

2021-09-03 16:02 UTC, BarnyShergold requested changes
A few suggested changes

2021-09-03 16:02 UTC, BarnyShergold commented on src/sales/rma-customer-experience.md
> +If the order contains several items and customer wants to return for example two out of four, they click **Add Item To Return** button, selects an item and sets all mentioned options.
```suggestion
If the order contains several items and the customer wants to return, for example, two out of four, they click the  **Add Item To Return** button, then select an item and then set all mentioned options.
```

2021-09-06 13:50 UTC, DmitryTsymbal commented on src/sales/rma-customer-experience.md
> +If the order contains several items and customer wants to return for example two out of four, they click **Add Item To Return** button, selects an item and sets all mentioned options.
Changes applied.
Thanks!

2021-09-07 09:00 UTC, BarnyShergold approved these changes
Thanks!

2021-09-08 15:39 UTC, leslietilling approved these changes

2021-09-08 15:40 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-08 15:41 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-09-09 16:13 UTC, merged