Add the missing field for the delivery methods
magento/merchdocs pull request #1487
Opened 2021-09-06 13:58 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request adds the missing field for the delivery methods:
- Flat Rate
- Table Rates

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/shipping/shipping-table-rate.html
https://docs.magento.com/user-guide/shipping/shipping-flat-rate.html

2021-09-06 14:46 UTC, BarnyShergold requested changes
Nice clarification - one small change needed

2021-09-06 14:46 UTC, BarnyShergold commented on src/shipping/shipping-table-rate.md
> +1. Set **Show Method if Not Applicable** to `Yes` if you want to show Table Rates all time
```suggestion
1. Set **Show Method if Not Applicable** to `Yes` if you want to show Table Rates all the time
```

2021-09-06 15:26 UTC, ZhovnirMaria commented on src/shipping/shipping-table-rate.md
> +1. Set **Show Method if Not Applicable** to `Yes` if you want to show Table Rates all time
Done, please check) Thanks ☺️

2021-09-07 08:43 UTC, BarnyShergold approved these changes
Thanks!

2021-09-08 13:39 UTC, dobooth approved these changes

2021-09-08 13:39 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-09-08 13:40 UTC, magento-engcom-team commented
@dobooth the pull request successfully imported.

2021-09-09 16:13 UTC, merged