Describe how to Configure New Order Email Notification
magento/merchdocs pull request #1491
Opened 2021-09-08 12:49 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request describes how to Configure New Order Email Notification

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/sales/order-status-notification.html

2021-09-08 14:58 UTC, BarnyShergold requested changes
A few suggested changes.

Please note - if a suggested change is accepted then it is better to use the "accept" option on the PR so it's easy to see - if you add the changes manually and then push, then they have to be rechecked as it's possible a small mistake could be made.

Thanks!

2021-09-08 14:58 UTC, BarnyShergold commented on src/sales/order-status-notification.md
> +1. In the left panel, expand **Sales** and choose **Sales Email** underneath.
```suggestion
1. In the left panel, expand **Sales** and choose **Sales Emails** underneath.
```

2021-09-08 14:58 UTC, BarnyShergold commented on src/sales/order-status-notification.md
> +    - Customer Support
Add -
Custom Email 1
Custom Email 2

2021-09-08 14:58 UTC, BarnyShergold commented on src/sales/order-status-notification.md
> +1. Choose the **New Order Confirmation Template** for `Customers` and `Guests`.
List the three options in full -
New Order (Default)
New Pickup Order 
New Pickup Order For Guest

2021-09-08 14:58 UTC, BarnyShergold commented on src/sales/order-status-notification.md
> +1. To notify about the new order, enter the email address to **Send Order Email Copy To**.
```suggestion
1. To notify another person (e.g. Admin) about the new order, enter the email address to **Send Order Email Copy To**. It is possible to add multiple email addresses here if more than one additional recipient is required.
```

2021-09-08 14:58 UTC, BarnyShergold commented on src/sales/order-status-notification.md
> +    |Bcc|Only one email about the new order will be sent to both customer and the recipient, but the customer won't see that the email they received was also sent to the recipient.|
```suggestion
    |Bcc|Only one email about the new order will be sent to both customer and the additional recipient, but the customer won't see that the email they received was also sent to the additional recipient.|
```

2021-09-08 14:58 UTC, BarnyShergold commented on src/sales/order-status-notification.md
> +    |Separate Email|Two separate emails will be sent to the recipient and the customer.|
```suggestion
    |Separate Email|Two separate emails will be sent, one to the recipient and one to the customer.|
```

2021-09-13 17:11 UTC, ZhovnirMaria commented
Done ✅ Thanks!

2021-09-14 15:07 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-14 15:11 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-16 17:01 UTC, merged