Add description about removing a page
magento/merchdocs pull request #1493
Opened 2021-09-09 08:10 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) adds description about removing a page

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/cms/page-duplicate.html

2021-09-09 08:31 UTC, BarnyShergold requested changes
Two small correction - nice addition

2021-09-09 08:31 UTC, BarnyShergold commented on src/cms/page-duplicate.md
> +There are two ways to remove created page. You can remove it from _Pages_ grid, or from the _Edit_ page.
```suggestion
There are two ways to remove a created page. You can remove it from _Pages_ grid or from the _Edit_ page.
```

2021-09-09 08:33 UTC, EvheniiaKolkhiieva commented
Hi @BarnyShergold , thank you for reviewing! Done ✅

2021-09-09 08:52 UTC, BarnyShergold approved these changes
That was a quick turnround!

2021-09-09 16:43 UTC, leslietilling reviewed
Just some style edits

2021-09-09 16:43 UTC, leslietilling commented on src/_data/toc/content.yml
> +      - label: Duplicating & Deleting a Page
We don't use ampersands (although the UI unfortunately has some)

```suggestion
      - label: Duplicating and Deleting a Page
```

2021-09-09 16:43 UTC, leslietilling commented on src/cms/page-duplicate.md
> +title: Duplicating & Deleting a Page
```suggestion
title: Duplicating and Deleting a Page
```

2021-09-09 16:43 UTC, leslietilling commented on src/cms/page-duplicate.md
> +## Delete a Page
```suggestion
## Delete a page
```

2021-09-09 16:43 UTC, leslietilling commented on src/cms/page-duplicate.md
> +1. In the menu bar click <span class="btn">Delete Page</span>.
```suggestion
1. In the button bar, click <span class="btn">Delete Page</span>.
```

2021-09-09 16:44 UTC, leslietilling approved these changes

2021-09-09 16:46 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-10 15:03 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-10 15:04 UTC, magento-engcom-team commented
@leslietilling the pull request successfully imported.

2021-09-13 17:09 UTC, merged