Update the "Create a Newsletter Template" flow on the Newsletter Templates page
magento/merchdocs pull request #1500
Opened 2021-09-14 09:18 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request updates the "Create a Newsletter Template" flow on the Newsletter Templates page

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/variables-predefined.html

2021-09-14 15:29 UTC, leslietilling requested changes
Edits for grammar and style

2021-09-14 15:29 UTC, leslietilling commented on src/marketing/variables-predefined.md
> +## Restore Html Version
```suggestion
## Restore the HTML version
```

2021-09-14 15:29 UTC, leslietilling commented on src/marketing/variables-predefined.md
> +1. To save the HTML version of template, click <span class="btn">Save Template</span>.
```suggestion
1. To save the HTML version of the template, click <span class="btn">Save Template</span>.
```

2021-09-14 15:29 UTC, leslietilling commented on src/marketing/variables-predefined.md
> +1. When prompted to strip tags, click OK.
```suggestion
1. When prompted to strip tags, click **OK**.
```

2021-09-14 15:29 UTC, leslietilling commented on src/marketing/variables-predefined.md
> +## Convert the Template to Plain Text
```suggestion
## Convert the template to plain text
```

2021-09-16 13:54 UTC, leslietilling approved these changes

2021-09-16 13:55 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-16 14:05 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-16 14:06 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-09-16 17:01 UTC, merged