Added additional information to search term page
magento/merchdocs pull request #1513
Opened 2021-09-15 11:53 UTC by DmitryTsymbal

## Purpose of this pull request

Added additional information to search term page

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/search-terms-add.html

2021-09-16 14:35 UTC, leslietilling requested changes
Edits for style and clarity

2021-09-16 14:35 UTC, leslietilling commented on src/marketing/search-terms-add.md
>  ## Delete a Search Term
We should probably fix capitalization in other parts of page too. "search term" is not really a proper noun and subheadings should be sentence case.

```suggestion
## Delete a search term
```

2021-09-16 14:35 UTC, leslietilling commented on src/marketing/search-terms-add.md
> +There are two methods for deleting a Search Term -- from the grid and on the edit page.
```suggestion
There are two methods for deleting a search term -- from the grid and on the edit page.
```

2021-09-16 14:35 UTC, leslietilling commented on src/marketing/search-terms-add.md
> +**Method 1:** In the Search Terms grid.
```suggestion
**Method 1:** In the _Search Terms_ grid
```

2021-09-16 14:35 UTC, leslietilling commented on src/marketing/search-terms-add.md
> +**Method 2:** On the Edit a Search Term page.
```suggestion
**Method 2:** On the _Edit a Search Term_ page
```

2021-09-16 14:35 UTC, leslietilling commented on src/marketing/search-terms-add.md
> +1. Click <span class="btn">Delete Search</span> button.
```suggestion
1. Click <span class="btn">Delete Search</span>.
```

2021-09-16 14:35 UTC, leslietilling commented on src/marketing/search-terms-add.md
> +## Grid column description
```suggestion
## Grid columns
```

2021-09-16 14:35 UTC, leslietilling commented on src/marketing/search-terms-add.md
> +|Actions|Opens the product in Edit mode.|
```suggestion
|Actions|Opens the product in edit mode.|
```

2021-09-16 14:35 UTC, leslietilling commented on src/marketing/search-terms-add.md
> +|Suggested Terms|Determines if the query displays in suggested terms.|
```suggestion
|Suggested Terms|Determines if the query result displays suggested terms.|
```

2021-09-17 15:44 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-17 16:25 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-09-17 16:25 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2021-09-17 17:35 UTC, merged