Added additional information about updating customer's store credit balance
magento/merchdocs pull request #1520
Opened 2021-09-17 08:24 UTC by DmitryTsymbal

…alance

## Purpose of this pull request

Added additional information about updating customer's store credit balance

## Affected documentation pages

https://docs.magento.com/user-guide/customers/store-credit-using.html

2021-09-17 15:31 UTC, leslietilling requested changes
Edits for style and clarity

2021-09-17 15:31 UTC, leslietilling commented on src/customers/store-credit-using.md
> +1. To notify customer about balance updating check **Notify Customer by Email** checkbox and choose the store view from **Send Email Notification From the Following Store View**.
```suggestion
1. To notify the customer about the balance update, select the **Notify Customer by Email** checkbox and choose the store view from **Send Email Notification From the Following Store View**.
```

2021-09-17 15:31 UTC, leslietilling commented on src/customers/store-credit-using.md
> +1. Enter the **Comment**
```suggestion
1. Enter a **Comment** about the change.
```

2021-09-17 15:31 UTC, leslietilling commented on src/customers/store-credit-using.md
> +Updated Balance entity should be displayed in **Balance History**
```suggestion
Updated Balance entity should be displayed in **Balance History**.
```

2021-09-17 15:31 UTC, leslietilling commented on src/customers/store-credit-using.md
> +1. Choose the website (storefront) for which the balance will be associated.
```suggestion
1. Choose the website (storefront) to associate with the balance.
```

2021-09-23 16:02 UTC, leslietilling approved these changes

2021-09-23 16:05 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-23 16:13 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-23 17:34 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-09-23 17:34 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-09-29 16:54 UTC, merged