ACP2E-228: [Documentation] Add notice that the cookie path can't contain any cookie parameters except path to folders
magento/merchdocs pull request #1535
Opened 2021-10-01 19:28 UTC by vkolesny

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

According to the investigation in the ACP2E-223, in Magento Admin it is implemented the validation that the Cookie Path field must contain only the path and no other cookie parameters.
But it is not reflected in the Magento documentation.
So it confuses some Merchants.
So it should be mentioned in the Magento 2.4.x User Guide to let them know that they cannot use any other cookie parameters except the path to folders on their server.

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

Magento 2.4.x

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

-Magento Open Source

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- ...

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/configuration/general/web.html
- https://docs.magento.com/user-guide/stores/compliance-cookie-restriction-mode.html

2021-10-01 21:57 UTC, leslietilling requested changes
Some proposed edits for language and clarity

2021-10-01 21:57 UTC, leslietilling commented on src/configuration/general/web.md
> +|Cookie Path|Store View|Specifies the folders on the server where Commerce cookies can be used. To make Commerce cookies available everywhere in the installation, set the Cookie Path to a single forw
```suggestion
|Cookie Path|Store View|Specifies the folders on the server where Commerce cookies can be used. To make Commerce cookies available everywhere in the installation, set the Cookie Path to a single forward slash: `/`. This value can contain only the cookie path, and **_cannot_** contain any other cookie parameters.|
```

2021-10-01 21:57 UTC, leslietilling commented on src/configuration/general/web.md
> +|Cookie Domain|Store View|Determines if Commerce cookies are available to subdomains. For example, to support mysubdomain.domain.com, enter the name of your domain with a period at the beginning, lik
```suggestion
|Cookie Domain|Store View|Determines if Commerce cookies are available to subdomains. For example, to support mysubdomain.domain.com, enter the name of your domain with a period at the beginning, like `.domain.com`. This value can contain only the cookie domain, and **_cannot_** contain any other cookie parameters.
```

2021-10-01 21:57 UTC, leslietilling commented on src/stores/compliance-cookie-restriction-mode.md
> +    - If you want to make cookies available to other folders, enter the **Cookie Path**. To make the cookies available anywhere in the site, enter a forward slash (`/`). It can't contain any other co
```suggestion
    - If you want to make cookies available to other folders, enter the **Cookie Path**. To make the cookies available anywhere in the site, enter a forward slash (`/`). This value can contain only the cookie path, and **_cannot_** contain any other cookie parameters.
```

2021-10-01 21:57 UTC, leslietilling commented on src/stores/compliance-cookie-restriction-mode.md
> +    - To make the cookies available to a subdomain, enter the subdomain name in the **Cookie Domain** field (`subdomain.yourdomain.com`). To make cookies available to all subdomains, enter the domain
```suggestion
    - To make the cookies available to a subdomain, enter the subdomain name in the **Cookie Domain** field (`subdomain.yourdomain.com`). To make cookies available to all subdomains, enter the domain name preceded by a period (`.yourdomain.com`). This value can contain only the cookie domain, and **_cannot_** contain any other cookie parameters.
```

2021-10-04 14:59 UTC, vkolesny commented on src/configuration/general/web.md
> +|Cookie Path|Store View|Specifies the folders on the server where Commerce cookies can be used. To make Commerce cookies available everywhere in the installation, set the Cookie Path to a single forw
Requested changes were applied successfully

2021-10-04 15:00 UTC, vkolesny commented on src/stores/compliance-cookie-restriction-mode.md
> +    - If you want to make cookies available to other folders, enter the **Cookie Path**. To make the cookies available anywhere in the site, enter a forward slash (`/`). It can't contain any other co
Requested changes were applied successfully

2021-10-04 15:00 UTC, vkolesny commented on src/stores/compliance-cookie-restriction-mode.md
> +    - To make the cookies available to a subdomain, enter the subdomain name in the **Cookie Domain** field (`subdomain.yourdomain.com`). To make cookies available to all subdomains, enter the domain
Proposed changes were applied successfully

2021-10-04 15:06 UTC, vkolesny commented
All proposed edits were implemented successfully.
Could you please review?

2021-10-04 15:24 UTC, leslietilling approved these changes

2021-10-04 15:24 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-10-04 15:35 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-10-04 15:35 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-10-06 16:03 UTC, merged