Add description about the common types of breadcrumbs
magento/merchdocs pull request #1592
Opened 2021-10-27 13:21 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

This pull request (PR) adds description about the common types of breadcrumbs

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/catalog/navigation-breadcrumb-trail.html

## Links to Magento source code or PRs

_OPTIONAL. If this pull request references a file in a Magento codebase repository or a code PR, add it here._

- https://community.magento.com/t5/Magento-2-x-Programming/Breadcrumbs-in-Magento-2/td-p/101782

whatsnew
Added _Common types of breadcrumbs_ section to the [Breadcrumb Trail](https://docs.magento.com/user-guide/catalog/navigation-breadcrumb-trail.html) topic.

2021-11-03 15:22 UTC, dobooth approved these changes

2021-11-03 15:22 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-11-03 15:23 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2021-11-03 15:59 UTC, dobooth requested changes
Please rewrite per our conversation.

2021-11-19 17:12 UTC, leslietilling approved these changes
I will put in style/grammar edits.

2021-11-19 17:12 UTC, leslietilling commented on src/catalog/navigation-breadcrumb-trail.md
> +This kind of breadcrumbs are based on the category hierarchy set up on the site. The chains presented tell the user at what structural level they are. In this case, each text link is intended for a p
```suggestion
This type of breadcrumb is based on the category hierarchy set up on the site. The chains presented tell the user where in the structure they are. In this case, each text link is intended for a page that is one level higher than the previous one.
```

2021-11-19 17:12 UTC, leslietilling commented on src/catalog/navigation-breadcrumb-trail.md
> +This type of breadcrumb helps users easily see which category level they are in and provide easy navigation between catalog pages.
```suggestion
The advantage of this type is that users can easily see which category level they are in and have easy access to navigation between catalog pages.
```

2021-11-19 17:12 UTC, leslietilling commented on src/catalog/navigation-breadcrumb-trail.md
> +This type of breadcrumbs is useful when customers want to return to a previous page after selecting multiple filters on a category page.
```suggestion
The advantage of this type is that it is most helpful when customers want to return to a previous page after selecting multiple filters on a category page.
```

2021-11-19 17:12 UTC, leslietilling commented on src/catalog/navigation-breadcrumb-trail.md
> +This type of angry crumbs displays the attributes selected on the category page. The main difference from the previous types is that the attribute-based breadcrumbs represent the filters and options
```suggestion
This type of breadcrumb displays the attributes selected on the category page. The main difference from the other types is that the attribute-based breadcrumbs represent the filters and options you have selected in the navigation layer for certain products (such as price, quality, and color).
```

2021-11-19 17:17 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-19 17:19 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-11-22 20:40 UTC, merged