Add warning for users of Google reCAPTCHA version 3 with low score
magento/merchdocs pull request #1597
Opened 2021-10-28 20:36 UTC by fredden

## Purpose of this pull request

This pull request adds a warning regarding the implementation of Google reCAPTCHA within Magento, specifically regarding how version 3 has been implemented to completely block genuine users with a low score.

## Magento release version

This feature is present in Magento v2.4.

## Product editions

This change affects Magento Open Source and Adobe Commerce.

## Affected documentation pages

- https://docs.magento.com/user-guide/configuration/security/google-recaptcha-admin.html
- https://docs.magento.com/user-guide/configuration/security/google-recaptcha-storefront.html

## Additional information

I have not changed the 'recommended' labels in these documents although I do disagree with their current placement. I do not think that the current implementation of Google reCAPTCHA v3 in Magento is suitable for an ecommerce website.

2021-11-01 14:49 UTC, leslietilling requested changes
This is good information for merchants to know. Just some suggested edits for style and clarity.

2021-11-01 14:49 UTC, leslietilling commented on src/configuration/security/google-recaptcha-admin.md
> +When using version 3, a genuine user with low score will be unable to proceed; when using version 2, a genuine user with a low score will receive an challenge. Consider carefully if genuine users wit
```suggestion
When using reCAPTCHA version 3, a genuine user with low score cannot proceed. For version 2, a genuine user with a low score receives a challenge. Consider carefully if genuine users with a low score should have an opportunity to solve a challenge (version 2) or be completely blocked (version 3).
```

2021-11-01 14:49 UTC, leslietilling commented on src/configuration/security/google-recaptcha-storefront.md
> +When using version 3, a genuine user with low score will be unable to proceed; when using version 2, a genuine user with a low score will receive an challenge. Consider carefully if genuine users wit
```suggestion
When using reCAPTCHA version 3, a genuine user with low score cannot proceed. For version 2, a genuine user with a low score receives a challenge. Consider carefully if genuine users with a low score should have an opportunity to solve a challenge (version 2) or be completely blocked (version 3).
```

2021-11-01 21:31 UTC, fredden commented
Thanks for the suggestions.

2021-11-03 15:53 UTC, leslietilling approved these changes

2021-11-03 15:54 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-03 15:59 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-03 16:00 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-11-03 17:14 UTC, merged