Add missing tab and notices for the Product Settings block
magento/merchdocs pull request #1602
Opened 2021-11-03 16:48 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) adds missing tab and notices for the Product Settings block

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/catalog/settings.html

2021-11-08 19:06 UTC, leslietilling requested changes
syntax fix and minor edit

2021-11-08 19:06 UTC, leslietilling commented on src/catalog/settings.md
> +|{:.b2b-only}[Product In Shared Catalogs]({% link catalog/catalog-shared.md %})| Gives the ability to maintain gated shared catalogs with custom pricing for different companies and provides access to
Unfortunately, `{:.b2b-only}` does not work in tables

```suggestion
|<span class="b2b-only">[Product In Shared Catalogs]({% link catalog/catalog-shared.md %})</span>| Enables the ability to maintain shared catalogs with custom pricing for different companies, with access to two types of shared catalogs using different pricing structures.|
```

2021-11-18 18:50 UTC, leslietilling approved these changes

2021-11-18 18:53 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-18 18:54 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-11-22 20:40 UTC, merged