ACP2E-269: UPS shipping rate calculation error
magento/merchdocs pull request #1603
Opened 2021-11-05 20:46 UTC by thiaramus

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) is to clarify that Magento does not support shipping cost calculation by dimensional weight for FedEx and UPS out of the box.

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- Both

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- N/A

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/shipping/ups.html
- https://docs.magento.com/user-guide/shipping/fedex.html

## Links to Magento source code or PRs

_OPTIONAL. If this pull request references a file in a Magento codebase repository or a code PR, add it here._

- https://jira.corp.magento.com/browse/ACP2E-269

## Additional information

_OPTIONAL. What other information can you provide?_

2021-11-08 19:09 UTC, leslietilling requested changes
Edits for branding, etc.

2021-11-08 19:09 UTC, leslietilling commented on src/shipping/fedex.md
> +FedEx can use [dimensional weight]({% link shipping/weight-dimensional.md %}) to determine some shipping rates. However, Magento only supports weight based shipping cost calculation.
```suggestion
FedEx can use [dimensional weight]({% link shipping/weight-dimensional.md %}) to determine some shipping rates. However, Adobe Commerce and Magento Open Source support only weight-based shipping cost calculation.
```

2021-11-08 19:09 UTC, leslietilling commented on src/shipping/ups.md
> +UPS can use [dimensional weight]({% link shipping/weight-dimensional.md %}) to determine some shipping rates. However, Magento only supports weight based shipping cost calculation.
```suggestion
UPS can use [dimensional weight]({% link shipping/weight-dimensional.md %}) to determine some shipping rates. However, Adobe Commerce and Magento Open Source support only weight-based shipping cost calculation.
```

2021-11-10 15:34 UTC, thiaramus commented
Thank you for the corrections, @leslietilling !

2021-11-10 16:23 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-10 16:28 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-10 16:33 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-10 16:44 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-10 16:50 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-11-10 16:51 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2021-11-10 19:37 UTC, merged