Scheduling an Export: Described configuring export if remote server was selected. Updated entity types
magento/merchdocs pull request #1605
Opened 2021-11-08 10:02 UTC by DmitryTsymbal

## Purpose of this pull request

Described configuring export if remote server was selected. Updated entity types

## Affected documentation pages

https://docs.magento.com/user-guide/system/data-schedule-export.html

2021-11-10 17:37 UTC, leslietilling requested changes
minor edits for style and clarity

2021-11-10 17:37 UTC, leslietilling commented on src/system/data-schedule-export.md
> +1. If the **Remote FTP server** was selected enter connection credentials to the server and select additional settings:
```suggestion
1. If the **Remote FTP **  server is selected, enter connection credentials to the server and select additional settings:
```

2021-11-10 17:37 UTC, leslietilling commented on src/system/data-schedule-export.md
> +   - **FTP Host[:Port]**, enter remote ftp host address.
```suggestion
   - For **FTP Host[:Port]**, enter remote FTP host address.
```

2021-11-10 17:37 UTC, leslietilling commented on src/system/data-schedule-export.md
> +   - **User Name**, enter a username, to access the remote server.
```suggestion
   - For **User Name**, enter the username used to access the remote server.
```

2021-11-10 17:37 UTC, leslietilling commented on src/system/data-schedule-export.md
> +   - **Password**, enter a password of provided username account.
```suggestion
   - For **Password**, enter the password of the provided username account.
```

2021-11-10 17:37 UTC, leslietilling commented on src/system/data-schedule-export.md
> +   - **File Mode**, `Binary` or `ASCII`.
```suggestion
   - **File Mode**, `Binary` or `ASCII`.
```
```suggestion
   - For **File Mode**, choose `Binary` or `ASCII`.
```

2021-11-10 17:37 UTC, leslietilling commented on src/system/data-schedule-export.md
> +   - **Passive Mode**, `No` or `Yes`.
```suggestion
   - For **Passive Mode**, choose `No` or `Yes`.
```

2021-11-18 19:54 UTC, leslietilling approved these changes

2021-11-18 19:56 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-18 19:56 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-11-22 20:40 UTC, merged