ACP2E-160: [Cloud] Shipping prices quoted in UPS doesn't match Magento Checkout page
magento/merchdocs pull request #1609
Opened 2021-11-08 13:13 UTC by thiaramus

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) is to add a note about order price declaration for FedEx and UPS, since this affect the shipping costs.

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- N/A

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- N/A

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/shipping/fedex.html
- https://docs.magento.com/user-guide/shipping/ups.html

## Links to Magento source code or PRs

_OPTIONAL. If this pull request references a file in a Magento codebase repository or a code PR, add it here._

- https://jira.corp.magento.com/browse/ACP2E-160
- https://jira.corp.magento.com/browse/MC-43222

There have been no actual code changes, we are just documenting the existing behavior according to the product owner recommendation.

## Additional information

_OPTIONAL. What other information can you provide?_

2021-11-09 16:56 UTC, dobooth requested changes

2021-11-09 16:56 UTC, dobooth commented on src/shipping/fedex.md
> +Please note that Magento always declare the full order price to FedEx when calculating shipping charges. This behavior cannot be changed.
```suggestion
Magento always declares the full order price to FedEx when calculating shipping charges. This behavior cannot be changed.
```

2021-11-09 16:56 UTC, dobooth commented on src/shipping/ups.md
> +Please note that Magento does not declare the full order price to UPS when calculating shipping charges. This behavior cannot be changed.
```suggestion
Magento does not declare the full order price to UPS when calculating shipping charges. This behavior cannot be changed.
```

2021-11-10 17:39 UTC, leslietilling commented on src/shipping/ups.md
> +Magento does not declare the full order price to UPS when calculating shipping charges. This behavior cannot be changed.
```suggestion
Commerce does not declare the full order price to UPS when calculating shipping charges. This behavior cannot be changed.
```

2021-11-11 16:14 UTC, leslietilling approved these changes

2021-11-15 20:06 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-11-15 20:06 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2021-11-16 15:54 UTC, merged