Added additional information to Tax Rates page
magento/merchdocs pull request #1611
Opened 2021-11-08 13:50 UTC by DmitryTsymbal

## Purpose of this pull request

Added additional information to Tax Rates page: Tax titles for each storeview/Deleting tax rate

## Affected documentation pages

https://docs.magento.com/user-guide/tax/tax-zones-rates.html

2021-11-09 16:58 UTC, dobooth requested changes

2021-11-09 16:58 UTC, dobooth commented on src/tax/tax-zones-rates.md
> +![]({% link images/images/tax-rate-new-tax-titles.png %}){: .zoom}
I don't think we need a new image here. Please remove it.

2021-11-09 16:58 UTC, dobooth commented on src/tax/tax-zones-rates.md
> +## Delete Tax Rate
```suggestion
## Delete tax rate
```

2021-11-10 08:16 UTC, DmitryTsymbal commented
Hello @dobooth , thank you for the review, I have applied the requested changes, please check it.
Thanks!

2021-11-15 20:03 UTC, dobooth approved these changes

2021-11-15 20:03 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-11-15 20:04 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2021-11-16 15:54 UTC, merged