Added additional information to Invitations page
magento/merchdocs pull request #1614
Opened 2021-11-09 09:45 UTC by DmitryTsymbal

## Purpose of this pull request

Added additional information to Invitations page

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/invitations.html

2021-11-10 17:48 UTC, leslietilling requested changes
minor edits for style and clarity

2021-11-10 17:48 UTC, leslietilling commented on src/marketing/invitations.md
> +1. On the next screen, enter email addresses to invite new customers, add a custom message, choose a sender, and select an invitee group. If you have multiple store views, set the **Send From** choos
```suggestion
1. On the next screen, enter email addresses to invite new customers, add a custom message, choose a sender, and select an invitee group.

   If you have multiple store views, use the **Send From** option to specify the store view from which an invitation is sent.
```

2021-11-10 17:48 UTC, leslietilling commented on src/marketing/invitations.md
> +## Discard Invitations for single entity
```suggestion
## Discard invitations for single entity
```

2021-11-10 17:48 UTC, leslietilling commented on src/marketing/invitations.md
> +## Discard Invitations for multiple entities
```suggestion
## Discard invitations for multiple entities
```

2021-11-10 17:48 UTC, leslietilling commented on src/marketing/invitations.md
> +1. Find the invitations to be discarded and select them.
```suggestion
1. Find and select the invitations to be discarded.
```

2021-11-10 17:48 UTC, leslietilling commented on src/marketing/invitations.md
> +1. Choose **Discard Selected** in the __Actions__ drop-down and click **Submit**.
```suggestion
1. At the top-left, use the **Actions** menu to choose **Discard Selected** and click **Submit**.
```

2021-11-11 07:35 UTC, DmitryTsymbal commented
Hello @leslietilling , thank you for the review. I have applied requested changes, please check.
Thanks!

2021-11-15 17:42 UTC, leslietilling approved these changes

2021-11-15 18:03 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-15 18:04 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-11-16 15:54 UTC, merged