ACP2E-338: [Documentation] Add notice that mini cart may be not synchronized across the multiple devices and browsers
magento/merchdocs pull request #1624
Opened 2021-11-18 22:25 UTC by vkolesny

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

As a result of the Cache invalidation logic improvement for the customer section on Magento Cloud in scope of the MC-18191 ticket it was introduced following known acceptable Mini Cart drawback:
-In some cases registered customer Mini Cart may be not synchronized across the multiple devices and browsers automatically. To synchronize your registered customer Mini Cart in such cases, please open the Shopping Cart page on that another device or browser.

This information is described in the internal documentation:
https://wiki.corp.magento.com/pages/viewpage.action?spaceKey=MCP&title=Implementation+of+Cache+invalidation+logic+for+customer+section

So Merchants should be informed about such case and that this is an expected behavior in the external documentation as well:
https://docs.magento.com/user-guide/sales/mini-cart.html

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

Magento 2.4.x

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

Applicable to both Magento Open Source and Adobe Commerce

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

No

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

https://docs.magento.com/user-guide/sales/mini-cart.html

2021-11-19 17:22 UTC, leslietilling requested changes
Suggested edits for clarity and grammar.

2021-11-19 17:22 UTC, leslietilling commented on src/sales/mini-cart.md
> +In some cases _registered_ customer Mini Cart may be not synchronized across the multiple devices and browsers automatically. To synchronize your Mini Cart in such cases, just open the [Shopping Cart
```suggestion
For a _registered_ customer, there are cases when the Mini Cart may not be synchronized across the multiple devices and browsers automatically. To synchronize the Mini Cart in such cases, the customer can simply open the [Shopping Cart]({% link sales/cart.md %}) page on that device or browser.
```

2021-11-19 19:35 UTC, vkolesny commented on src/sales/mini-cart.md
> +In some cases _registered_ customer Mini Cart may be not synchronized across the multiple devices and browsers automatically. To synchronize your Mini Cart in such cases, just open the [Shopping Cart
Suggested changes were committed

2021-11-22 17:01 UTC, leslietilling approved these changes

2021-11-22 17:01 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-22 17:03 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-11-22 20:40 UTC, merged