Update the Wish List Search page information and describe the difference between private and public wishlist
magento/merchdocs pull request #1629
Opened 2021-11-19 11:27 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request:
- Updates the Wish List Search page information 
- Describes the difference between private and public wishlist

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- yes

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/wishlist-search.html
https://docs.magento.com/user-guide/customers/account-dashboard-my-wish-list.html

2021-11-19 17:32 UTC, leslietilling requested changes
Minor edits for style and clarity

2021-11-19 17:32 UTC, leslietilling commented on src/marketing/wishlist-search.md
> +## How to find a customer's wishlist
```suggestion
## Find a customer's wishlist
```

2021-11-19 17:32 UTC, leslietilling commented on src/customers/account-dashboard-my-wish-list.md
> +    The main difference between `Public` and `Private` wishlists is that private wishlists are not searchable through [wishlists]({% link marketing/wishlist-search.md %}#how-to-find-a-customers-wishl
```suggestion
    The main difference between `Public` and `Private` wishlists is that private wishlists are not searchable through [wishlists]({% link marketing/wishlist-search.md %}#find-a-customers-wishlist).
```

2021-11-19 17:32 UTC, leslietilling commented on src/marketing/wishlist-search.md
> +1. From the Wish List Search widget select a search option.
```suggestion
1. From the Wish List Search widget, select a search option.
```

2021-11-19 17:32 UTC, leslietilling commented on src/marketing/wishlist-search.md
> +   The **Wish List Search** page will opens, found wishlists are displayed in the search results section.
```suggestion
   The **Wish List Search** page opens and any matching wishlists are displayed in the search results section.
```

2021-11-19 17:32 UTC, leslietilling commented on src/marketing/wishlist-search.md
> +   Only public wishlists can be displayed in search results, customer`s privat wishlists are not publicly viewable.
```suggestion
   Only public wishlists are displayed in search results---customers' private wishlists are not publicly viewable.
```

2021-11-19 17:32 UTC, leslietilling commented on src/marketing/wishlist-search.md
> +   For each customer's wishlist displays the owner name and the date of the last wishlist update.
```suggestion
   The owner name and the date of the last update is  displayed for each wishlist.
```

2021-11-19 17:32 UTC, leslietilling commented on src/marketing/wishlist-search.md
> +1. To add a product to your cart, check the box below the product and click <span class="btn">Add to Cart</span>.
```suggestion
1. To add a product to your cart, select the checkbox below the product and click <span class="btn">Add to Cart</span>.
```

2021-11-19 17:32 UTC, leslietilling commented on src/marketing/wishlist-search.md
> +   In addition, you can add items you like from another customer's wishlist to your own.
```suggestion
   You can also add items you like from another customer's wishlist to your own.
```

2021-11-22 08:53 UTC, ZhovnirMaria commented
@leslietilling I have updated my PR, please check) Thanks ☺️

2021-11-22 17:03 UTC, leslietilling approved these changes

2021-11-22 17:07 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-22 17:08 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-11-22 20:40 UTC, merged