ACP2E-342: [Documentation] Mention that partially refunded order remains in Processing status until all items are being shipped
magento/merchdocs pull request #1632
Opened 2021-11-19 22:40 UTC by vkolesny

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) is to mention in the Order Status documentation that partially refunded order remains in Processing status until all ordered items (including refunded items) are being shipped.
This means that order status will not be changed to Complete, while at least 1 order item is not shipped.
This behavior was confirmed by the Product Owner in the following JIRA comment:
https://jira.corp.magento.com/browse/MAGETWO-95724?focusedCommentId=1055519&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1055519

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

Magento 2.4.x

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

Both Magento Open Source and Adobe Commerce

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

No

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/sales/order-status.html

2021-11-22 17:22 UTC, leslietilling requested changes
Just some tweaking for clarity and language

2021-11-22 17:22 UTC, leslietilling commented on src/sales/order-status.md
> +Partially refunded order remains in `Processing` status until **_all_** ordered items (including refunded items) are being shipped. Such order status will not be changed to `Complete`, while at least
```suggestion
A partially refunded order remains in `Processing` status until **_all_** ordered items (including refunded items) are shipped. The order status does not change to `Complete` when even one order item is not yet shipped.
```

2021-11-23 01:56 UTC, vkolesny commented on src/sales/order-status.md
> +Partially refunded order remains in `Processing` status until **_all_** ordered items (including refunded items) are being shipped. Such order status will not be changed to `Complete`, while at least
Suggestions successfully committed.

2021-11-23 16:56 UTC, leslietilling approved these changes

2021-11-23 16:58 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-23 16:58 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-12-01 16:13 UTC, merged