ACP2E-346: [Documentation] Add final minimum(maximum) price calculation formula into number of documents
magento/merchdocs pull request #1635
Opened 2021-11-23 01:39 UTC by vkolesny

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

According to the Product Owner clarification:
https://jira.corp.magento.com/browse/MC-41581?focusedCommentId=1660777&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1660777

And according to the existing internal documentation:
https://wiki.corp.magento.com/display/SUSENG/Price+calculation+for+indexer#Pricecalculationforindexer-SimpleProductwithcustomoptions+tier(grouped)price

We should inform Merchants in the external documentation about minimum(maximum) product price calculation formula:
Final Min(Max) Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(Min Price per each required custom option)

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

Magento 2.4.x

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

Both Magento Open Source and Adobe Commerce

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

B2B extension, but only in scope of this document update:
https://docs.magento.com/user-guide/catalog/catalog-shared-pricing-structure.html

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/catalog/catalog-shared-pricing-structure.html
- https://docs.magento.com/user-guide/marketing/price-rules-catalog-create.html
- https://docs.magento.com/user-guide/catalog/product-price-group.html
- https://docs.magento.com/user-guide/catalog/product-price-special.html
- https://docs.magento.com/user-guide/catalog/product-price-tier.html

2021-11-23 16:56 UTC, leslietilling requested changes
Just slight editorial tweaks and formatting for formula

2021-11-23 16:56 UTC, leslietilling commented on src/catalog/catalog-shared-pricing-structure.md
> +| Fixed | Specifies the final product price. For example, if you enter a fixed price of $10.00, the price in the storefront for the corresponding company is $10.00. **Note:** Minimum value among Base
```suggestion
| Fixed | Specifies the final product price. For example, if you enter a fixed price of $10.00, the price in the storefront for the corresponding company is $10.00. **_Note:_** The minimum value between the Base Price and the entered Fixed value is used as the final product price. |
```

2021-11-23 16:56 UTC, leslietilling commented on src/catalog/product-price-group.md
> +The **_final_** product price is calculated as the **_minimum_** relevant price, by the formula: <br/>Final Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(
```suggestion
The **_final_** product price is calculated as the **_minimum_** relevant price, using the following formula: <br/>`Final Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(Min Price per each required custom option)`
```

2021-11-23 16:56 UTC, leslietilling commented on src/catalog/product-price-special.md
> +The **_final_** product price is calculated as the **_minimum_** relevant price, by the formula: <br/>Final Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(
```suggestion
The **_final_** product price is calculated as the **_minimum_** relevant price, using the following formula: <br/>`Final Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(Min Price per each required custom option)`
```

2021-11-23 16:56 UTC, leslietilling commented on src/catalog/product-price-tier.md
> +The **_final_** product price is calculated as the **_minimum_** relevant price, by the formula: <br/>Final Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(
```suggestion
The **_final_** product price is calculated as the **_minimum_** relevant price, using the following formula: <br/>`Final Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(Min Price per each required custom option)`
```

2021-11-23 16:56 UTC, leslietilling commented on src/marketing/price-rules-catalog-create.md
> +    _Regular price_ refers to the base product price without any advanced pricing (special/tier/group) or promotional discounts. _Final price_ refers to the discounted price that appears in the shopp
```suggestion
    _Regular price_ refers to the base product price without any advanced pricing (special/tier/group) or promotional discounts. _Final price_ refers to the discounted price that appears in the shopping cart. <br/>The **_final_** product price is calculated as the **_minimum_** relevant price, using the following formula: <br/>`Final Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(Min Price per each required custom option)`
```

2021-11-23 16:56 UTC, leslietilling commented on src/marketing/price-rules-catalog-create.md
> +|Apply|Determines the type of calculation that is applied to the purchase. Options: <br/>**Apply as percentage of original** - Discounts item by subtracting a percentage of the regular price. <br/>**
```suggestion
|Apply|Determines the type of calculation that is applied to the purchase. Options: <br/>**Apply as percentage of original** - Discounts item by subtracting a percentage of the regular price. <br/>**Apply as fixed amount** - Discounts item by subtracting a fixed amount from the regular price. <br/>**Adjust final price to this percentage** - Adjusts the final price by a percentage of the regular price. <br/>**Adjust final price to discount value** - Sets the final price to a fixed, discounted amount. <br/><br/>**_Note:_** Regular price refers to the base product price without any advanced pricing (special/tier/group) or promotional discounts. Final price refers to the discounted price that appears in the shopping cart. <br/>The **_final_** product price is calculated as the **_minimum_** relevant price, using the following formula: <br/>`Final Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(Min Price per each required custom option)`|
```

2021-11-23 19:54 UTC, vkolesny commented on src/catalog/catalog-shared-pricing-structure.md
> +| Fixed | Specifies the final product price. For example, if you enter a fixed price of $10.00, the price in the storefront for the corresponding company is $10.00. **Note:** Minimum value among Base
Committed

2021-11-23 19:54 UTC, vkolesny commented on src/catalog/product-price-special.md
> +The **_final_** product price is calculated as the **_minimum_** relevant price, by the formula: <br/>Final Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(
Committed

2021-11-23 19:54 UTC, vkolesny commented on src/marketing/price-rules-catalog-create.md
> +    _Regular price_ refers to the base product price without any advanced pricing (special/tier/group) or promotional discounts. _Final price_ refers to the discounted price that appears in the shopp
Committed

2021-11-23 19:55 UTC, vkolesny commented on src/catalog/product-price-group.md
> +The **_final_** product price is calculated as the **_minimum_** relevant price, by the formula: <br/>Final Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(
Committed

2021-11-23 19:55 UTC, vkolesny commented on src/catalog/product-price-tier.md
> +The **_final_** product price is calculated as the **_minimum_** relevant price, by the formula: <br/>Final Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(
Committed

2021-11-29 18:18 UTC, leslietilling approved these changes

2021-11-29 18:19 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-29 18:20 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-12-01 16:13 UTC, merged