ACP2E-348: [Documentation] Add notice into the documentation that new product image is always assigned and visible in all Store Views
magento/merchdocs pull request #1636
Opened 2021-11-23 03:37 UTC by vkolesny

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

In scope of MC-41865 and MC-41693 issues investigation following Product Owner clarification was given:
https://jira.corp.magento.com/browse/MC-41693?focusedCommentId=1664621&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1664621

Following notice should be added in the Uploading Product Images document:
`New product images are **_always_** uploaded and visible in **_all_** Store Views. Even if they are uploaded not in the `All Store Views` scope. <br/>To hide any chosen product image from some specific `Store View`, you must switch to this `Store View`, click on the `Hide from Product Page` checkbox for this image, and click <span class="btn">Save</span>.`

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

Magento 2.4.x

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

Both Magento Open Source and Adobe Commerce

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

No

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

https://docs.magento.com/user-guide/catalog/product-image-upload.html

2021-11-23 17:05 UTC, leslietilling requested changes
Editorial tweaks and some formatting

2021-11-23 17:05 UTC, leslietilling commented on src/catalog/product-image-upload.md
> +New product images are **_always_** uploaded and visible in **_all_** Store Views. Even if they are uploaded not in the `All Store Views` scope. <br/>To hide any chosen product image from some specif
```suggestion
   {:.bs-callout-info}
   New product images are **_always_** uploaded and visible in **_all_** store views, even if the `All Store Views` scope is not used for upload. <br/><br/>To hide any product image from a specific store view, you must switch to that Store View , select the **Hide from Product Page** checkbox for the image, and click <span class="btn">Save</span>.
```

2021-11-23 20:22 UTC, vkolesny commented on src/catalog/product-image-upload.md
> +New product images are **_always_** uploaded and visible in **_all_** Store Views. Even if they are uploaded not in the `All Store Views` scope. <br/>To hide any chosen product image from some specif
Committed

2021-11-29 18:21 UTC, leslietilling approved these changes

2021-11-29 18:22 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2021-11-29 18:23 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2021-12-01 16:13 UTC, merged