Update the Custom Order Status page information
magento/merchdocs pull request #1637
Opened 2021-11-24 14:02 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request updates the Custom Order Status page information

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/sales/order-status-custom.html

2021-11-29 18:26 UTC, leslietilling requested changes
just minor edits

2021-11-29 18:26 UTC, leslietilling commented on src/sales/order-status-custom.md
> +In addition to the preset order status settings, you can create custom order status settings of your own, assign them to order states, and set a default order status for order states. The order state
```suggestion
In addition to the preset order status settings, you can create your own custom order status settings, assign them to order states, and set a default order status for order states. The order state indicates the position of the order within the order processing workflow and the order status defines the state of the order. For example, you might need a custom order status such as `packaging”`, `backordered`, or a status that is specific to your needs. You can create a descriptive name for the custom status and assign it to the associated order state in the workflow.
```

2021-11-29 18:26 UTC, leslietilling commented on src/sales/order-status-custom.md
> +   Only the default order statuses are used in the order workflow. Non-default statuses can be set only in the order comments section in the admin panel.
```suggestion
   Only the default order statuses are used in the order workflow. Non-default statuses can be set only in the order comments section from the Admin.
```

2021-12-01 13:01 UTC, ZhovnirMaria commented
@leslietilling I have updated my PR, please check. Thanks ☺️

2021-12-03 15:53 UTC, dobooth approved these changes

2021-12-03 15:53 UTC, dobooth commented
@magento import pr to magento-devdocs/merchdocs

2021-12-03 15:54 UTC, m2-github-services commented
@dobooth the Pull Request is successfully imported.

2021-12-03 20:47 UTC, leslietilling approved these changes

2021-12-06 21:19 UTC, merged