Added additional information to reward points pages
magento/merchdocs pull request #1669
Opened 2022-01-12 10:45 UTC by DmitryTsymbal

## Purpose of this pull request

Added additional information to reward points pages:
- using reward points during the checkout
- notice, that points in cart price rules applies only to registered users.

## Affected documentation pages

https://docs.magento.com/user-guide/customers/account-dashboard-reward-points.html
https://docs.magento.com/user-guide/marketing/reward-points-price-rules.html

2022-01-12 17:01 UTC, leslietilling requested changes
Some edits for style and clarity.

2022-01-12 17:01 UTC, leslietilling commented on src/customers/account-dashboard-reward-points.md
> +If the available balance is greater than the order grand total, no additional payment methods is required.
```suggestion
If the available balance is greater than the order grand total, an additional payment method is not required.
```

2022-01-13 15:51 UTC, leslietilling approved these changes

2022-01-13 15:56 UTC, m2-github-services commented
@leslietilling an error occurred during the Pull Request import.

2022-01-13 16:37 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2022-01-13 16:37 UTC, m2-github-services commented
@leslietilling an error occurred during the Pull Request import.

2022-01-18 19:36 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2022-01-18 19:37 UTC, m2-github-services commented
@leslietilling an error occurred during the Pull Request import.

2022-01-19 15:58 UTC, sidolov commented
@magento import pr to magento-devdocs/merchdocs

2022-01-19 15:59 UTC, m2-github-services commented
@sidolov an error occurred during the Pull Request import.

2022-01-21 13:05 UTC, DmitryTsymbal commented
Closing this one, and opening https://github.com/magento/merchdocs/pull/1690 to avoid an errors during the import

2022-01-21 13:05 UTC, closed without merging