Describe how to cancel order with items from backorders salable qty
magento/merchdocs pull request #1671
Opened 2022-01-12 14:14 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request describes how to cancel order with items from backorders salable qty

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/catalog/inventory-backorders.html?itm_source=merchdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=back

2022-01-12 17:22 UTC, leslietilling requested changes
Proposed edits for style and clarity

2022-01-12 17:22 UTC, leslietilling commented on src/catalog/inventory-backorders.md
> +When a customer places an order using backorder qty, Inventory Management automatically subtracts qty from the salable quantity. If an order has not been shipped and is canceled the quantity returns
```suggestion
When a customer places an order using _backorder qty_, Inventory Management automatically subtracts the quantity from the salable quantity. If an order is not shipped and is canceled, the quantity returns to the aggregated virtual salable quantity. The **_canceled order quantity is not assigned to any of the sources_**, but is returned to the total number of products available for sale (_Salable Quantity_ column  on the products grid).
```

2022-01-12 17:44 UTC, ZhovnirMaria commented
@leslietilling please check, thanks ☺️

2022-01-13 15:56 UTC, leslietilling approved these changes

2022-01-13 16:39 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2022-01-13 16:40 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2022-01-21 20:06 UTC, merged