Expand the Import History topic with field description and instruction, how to download Imported/Error file
magento/merchdocs pull request #1672
Opened 2022-01-12 15:41 UTC by EvheniiaKolkhiieva

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) expands the Import History topic with field description and instruction, how to download Imported/Error file

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/system/data-import-history.html

2022-01-12 17:28 UTC, leslietilling requested changes
Minor edits

2022-01-12 17:28 UTC, leslietilling commented on src/system/data-import-history.md
> +1. Locate the export file at the downloads location for your web browser and open the file.
```suggestion
## Download the Imported/Error file

1. To download the _Imported/Error_ file, click **Download**.

1. Locate the export file at the downloads location for your web browser and open it.
```

2022-01-12 17:28 UTC, leslietilling commented on src/system/data-import-history.md
> +|Summary| The number of items created, updated and deleted, or the error message.|
```suggestion
|Summary| The number of items created, updated, and deleted, or the error message.|
```

2022-01-12 17:28 UTC, leslietilling commented on src/system/data-import-history.md
> +|ID| An nternal number used to designate a transfer.|
```suggestion
|ID| An internal number used to designate a transfer.|
```

2022-01-26 16:30 UTC, dobooth commented
@EvheniiaKolkhiieva

2022-02-07 16:57 UTC, leslietilling approved these changes

2022-02-07 16:59 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2022-02-11 11:44 UTC, merged