Describe difference between customer group and customer segment
magento/merchdocs pull request #1673
Opened 2022-01-12 16:10 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request:
- Describes difference between customer group and customer segment
- Corrects a typo in a word

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- yes

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/customers.html
https://docs.magento.com/user-guide/marketing/customer-segments.html

2022-01-12 17:34 UTC, leslietilling requested changes
Add link and minor edits for style

2022-01-12 17:34 UTC, leslietilling commented on src/marketing/customer-segments.md
> +To better understand the difference between customer groups and customer segments and where they are used, see:
```suggestion
To better understand the difference between [customer groups]({% link customers/customer-groups.md %}) and customer segments, note where they are used:
```

2022-01-12 17:34 UTC, leslietilling commented on src/marketing/customer-segments.md
> +||Customer Segment|Customer Grop|
```suggestion
||Customer segment|Customer group|
```

2022-01-12 17:34 UTC, leslietilling commented on src/marketing/customer-segments.md
> +|Category Permissions||✔️|
We use sentence case for table headings and items

```suggestion
|Catalog price rule||✔️|
|Cart price rule|✔️|✔️|
|Tier price||✔️|
|Related product rule|✔️||
|Dynamic block|✔️||
|Reward exchange rates||✔️|
|Category permissions||✔️|
```

2022-01-12 18:37 UTC, ZhovnirMaria commented
@leslietilling I have added some changes, please check. thanks ☺️

2022-01-13 16:43 UTC, leslietilling approved these changes

2022-01-13 16:50 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2022-01-18 20:21 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2022-01-18 20:22 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2022-01-21 20:06 UTC, merged