Update the Two-Factor Authentication page information
magento/merchdocs pull request #1682
Opened 2022-01-18 15:39 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request updates the Two-Factor Authentication page information

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/stores/security-two-factor-authentication.html

2022-01-18 21:18 UTC, leslietilling requested changes
Edits for style and clarity

2022-01-18 21:18 UTC, leslietilling commented on src/stores/security-two-factor-authentication.md
> +Two-factor authentication is widely used, and it is common to generate access codes for different websites on the same app. This ensures that only you is able to log in. If you lose your password or
```suggestion
Two-factor authentication is widely used, and it is common to generate access codes for different websites on the same app. This ensures that only you are able to log in to your user account. If you lose your password or a bot guesses it, two-factor authentication adds a layer of protection. For example, you might use Google Authenticator to generate codes for the _Admin_ of your store, your _Commerce account_ account, Google account, and so on.
```

2022-01-18 21:18 UTC, leslietilling commented on src/stores/security-two-factor-authentication.md
> +   |U2F Devices (Yubikey and others)| Physical device to authenticate, like [YubiKey](https://www.yubico.com/).|
```suggestion
   |U2F Devices (Yubikey and others)| Uses a physical device to authenticate, such as [YubiKey](https://www.yubico.com/).|
```

2022-01-20 10:28 UTC, ZhovnirMaria commented
Hi @leslietilling, please check, thanks ☺️

2022-01-20 19:50 UTC, leslietilling approved these changes

2022-01-20 19:51 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2022-01-21 15:33 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2022-01-21 15:34 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2022-01-21 20:06 UTC, merged