Add base thing to remember to the Websites, Stores, and Views page
magento/merchdocs pull request #1684
Opened 2022-01-19 11:05 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request adds base thing to remember to the Websites, Stores, and Views page

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/stores/websites-stores-views.html

2022-01-19 18:55 UTC, leslietilling requested changes
Edits for style and clarity

2022-01-19 18:55 UTC, leslietilling commented on src/stores/websites-stores-views.md
> +1. The main purpose of the store view is to set translation information and currency symbols.
```suggestion
When working with websites, stores, and store views, keep the following in mind:

- Commerce instances have a cascading model: global → website → store → store view.
- Every website has at least one default store and store view.
- Each store view can have a different base URL.
- The primary function of a website is top-level feature configuration.
- The primary function of a store is root category configuration.
- The primary function of a store view is translation information and currency symbol configuration.
```

2022-01-20 10:22 UTC, ZhovnirMaria commented
@leslietilling hi! Please check, thanks ☺️

2022-01-20 19:44 UTC, leslietilling approved these changes

2022-01-20 19:44 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2022-01-20 19:46 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2022-01-21 20:06 UTC, merged