Edit pages of the Operations pages
magento/merchdocs pull request #1693
Opened 2022-01-21 14:57 UTC by ZhovnirMaria

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request edit pages of the Operations pages

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/system/data-export.html
https://docs.magento.com/user-guide/stores/security-two-factor-authentication-manage.html#:~:text=Select%20the%20user%20and%20open,Reset%20and%20OK%20to%20confirm

2022-01-21 18:04 UTC, dobooth requested changes

2022-01-21 18:04 UTC, dobooth commented on src/system/data-export.md
> +Special characters—such as the equal sign, greater and less than symbols, single and double quotes, backslash, pipe, and ampersand symbols—can cause problems during data transfer. To ensure that such
I don't think this is a proper change. It is saying: If you need to the actual string to be `code="str"`, then wrap it in double quotes: `"code="str""`. Note that those backticks are markdown ticks to display the string as code.

2022-01-24 12:34 UTC, ZhovnirMaria commented
Hi, @dobooth please check, thanks ☺️

2022-01-26 14:03 UTC, dobooth approved these changes

2022-01-26 14:04 UTC, dobooth commented
@magento import code to magento-devdocs/merchdocs

2022-01-26 14:05 UTC, m2-github-services commented
@dobooth the branch with the code is successfully imported into the `magento-devdocs/merchdocs` repository. Branch name: `imported-ZhovnirMaria-merchdocs-1693`.

2022-01-28 13:28 UTC, merged