Added additional information to Coupon Codes page
magento/merchdocs pull request #1700
Opened 2022-02-14 09:58 UTC by DmitryTsymbal

## Purpose of this pull request

Added additional information to Coupon Codes page

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/price-rules-cart-coupon.html

2022-02-22 19:26 UTC, leslietilling requested changes
Edits for style and clarity

2022-02-22 19:26 UTC, leslietilling commented on src/marketing/price-rules-cart-coupon.md
> +Coupon codes can be exported to CSV or Excel XML files. For doing that select the needed file format and click <span class="btn">Export</span>.
```suggestion
You can export coupon codes to a CSV or Excel XML file by selecting the file format and clicking <span class="btn">Export</span>.
```

2022-02-22 19:26 UTC, leslietilling commented on src/marketing/price-rules-cart-coupon.md
> +To delete coupon codes, select needed codes from the list, select `Delete` from the **Actions** drop-down and click <span class="btn">Submit</span>.
```suggestion
To delete coupon codes, select one or more codes from the list, select `Delete` from the **Actions**  selector, and click <span class="btn">Submit</span>.
```

2022-02-22 19:26 UTC, leslietilling commented on src/marketing/price-rules-cart-coupon.md
> +   `Message is added to queue, wait to get your coupons soon` message is appeared. Make sure that cron is running on your server.
```suggestion
   The system displays `Message is added to queue, wait to get your coupons soon`. Make sure that cron is running on your server.
```

2022-02-22 19:26 UTC, leslietilling commented on src/marketing/price-rules-cart-coupon.md
> +   After the cron job was processed, the list of generated codes appears below.
```suggestion
   After the cron job was processed, the list of generated codes appears.
```

2022-02-24 16:09 UTC, leslietilling approved these changes

2022-02-24 16:12 UTC, m2-github-services commented
@leslietilling the branch with the code is successfully imported into the `magento-devdocs/merchdocs` repository. Branch name: `imported-DmitryTsymbal-merchdocs-1700`.

2022-02-26 00:33 UTC, merged