Added additional information to Customizable options page
magento/merchdocs pull request #1710
Opened 2022-03-01 10:30 UTC by DmitryTsymbal

## Purpose of this pull request

Added additional information to Customizable options page

## Affected documentation pages
https://docs.magento.com/user-guide/catalog/settings-advanced-custom-options.html

2022-03-01 15:40 UTC, leslietilling requested changes
Edits for style and clarity

2022-03-01 15:40 UTC, leslietilling commented on src/catalog/settings-advanced-custom-options.md
> +   - If the `Option Type` is **File**, enter the separated extensions, like: `png`, `jpg`, `gif` into **Compatible File Extensions** field, and image size in px. into **Maximum Image Size** field.
```suggestion
   - If the _Option Type_ is `File`, set the parameters for the file. For **Compatible File Extensions**, enter the valid extensions as comma-separated values (such as `png, jpg, gif`). For **Maximum Image Size**, enter the maximum image size in pixels.
```

2022-03-07 22:56 UTC, leslietilling approved these changes

2022-03-07 22:57 UTC, leslietilling commented
@magento import pr to magento-devdocs/merchdocs

2022-03-07 22:58 UTC, m2-github-services commented
@leslietilling the Pull Request is successfully imported.

2022-03-08 21:17 UTC, merged