Update yotpo-reviews-intro.md
magento/merchdocs pull request #719
Opened 2020-09-02 08:55 UTC by abigailyotpo

## Purpose of this pull request

Update for Magento 2.4.1 - we have a new Yotpo enhancement

This pull request (PR) ...

## Magento release version

- [ ] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- ...
- ...

2020-09-02 08:56 UTC, devops-devdocs commented
An admin must run tests on this PR before it can be merged.

2020-09-03 15:11 UTC, hickskenh requested changes

2020-09-03 15:11 UTC, hickskenh commented on src/marketing/yotpo-reviews-intro.md
> +- To enable customers to adjust when orders are synced to Yotpo, the following Yotpo extension functions have now been made programmatically accessible: getOrderCollection, setOrderCollectionLimit, a
```suggestion
- The following Yotpo extension functions are now programmatically accessible: `getOrderCollection`, `setOrderCollectionLimit`, and `addOrderCollection`. This enhancement enables customers to adjust when Magento orders are synced to Yotpo.
```

2020-09-03 15:12 UTC, hickskenh submitted a review, later dismissed

2020-09-03 15:13 UTC, hickskenh commented
@abigailyotpo review my suggested edit and commit.  Also, don't forget to sign the CLA.

2020-09-09 18:00 UTC, leslietilling approved these changes

2020-09-09 18:02 UTC, leslietilling commented
running tests

2020-09-09 18:20 UTC, merged