Clarifying Execution Time
magento/merchdocs pull request #796
Opened 2020-10-12 15:37 UTC by dobooth

## Purpose of this pull request

Fixes #775.

This pull request (PR) clarifies that "Execution Time" is a duration, not a timestamp.

## Magento release version

- 2.4.x

## Product editions

Is this update specific to a product edition?

- Magento Open Source only

## Affected documentation pages

https://docs.magento.com/user-guide/system/data-import-history.html

2020-10-12 15:49 UTC, leslietilling requested changes

2020-10-12 15:49 UTC, leslietilling commented on src/system/data-import-history.md
> +Note that "Execution Time" is the duration of the import process.
```suggestion
The _Execution Time_ is the duration of the import process.
```

2020-10-16 14:12 UTC, leslietilling approved these changes

2020-10-16 15:32 UTC, dobooth commented
running tests

2020-10-16 15:41 UTC, merged