Changes to dynamic block creation process
magento/merchdocs pull request #826
Opened 2020-10-26 15:21 UTC by SmVladyslav

## Purpose of this pull request

This pull request (PR) ...

## Magento release version

- [ ] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- ...
- ...

## Links to Magento source code or PRs

- ...
- ...

## Additional information

2020-10-26 19:36 UTC, hickskenh requested changes
requesting grammatical and punctuation corrections and resubmit for review

2020-10-26 19:36 UTC, hickskenh commented on src/cms/dynamic-blocks.md
> +   - If no **Segment** is created then **Dynamic Block** will be visible to everyone.
```suggestion
   - If no **Segment** is created, the **Dynamic Block** will be visible to everyone.
```

2020-10-26 19:36 UTC, hickskenh commented on src/cms/dynamic-blocks.md
> +   - If all **Customer Segments** that were assigned to **Dynamic Block** are deleted then its contents will be visible to everyone.
```suggestion
   - If all **Customer Segments** that were assigned to **Dynamic Block** are deleted, its contents will be visible to everyone.
```

2020-10-26 19:36 UTC, hickskenh commented on src/cms/dynamic-blocks.md
> +   - If **Customer** does not belong to any of **Segments** and **Dynamic Block** is created for All Segments then contents of **Dynamic Block** will still be displayed.
```suggestion
   - If **Customer** does not belong to any **Segments** and the **Dynamic Block** is created for All Segments, the contents of **Dynamic Block** will still be displayed.
```

2020-10-27 07:39 UTC, SmVladyslav commented
Corrected

2020-10-28 15:47 UTC, hickskenh approved these changes
approved

2020-10-28 15:48 UTC, hickskenh commented
running tests

2020-10-28 21:07 UTC, leslietilling commented
Hello @SmVladyslav  -- we are not allowed to merge unless you sign the Adobe CLA: http://opensource.adobe.com/cla.html

2020-11-02 18:58 UTC, hickskenh commented
running tests

2020-11-03 15:02 UTC, hickskenh commented
running tests

2020-11-03 18:23 UTC, hickskenh commented
running tests

2020-11-03 18:59 UTC, merged