Extend Import/Export documentation with Remote Storage
magento/merchdocs pull request #856
Opened 2020-11-13 15:05 UTC by adifucan

## Purpose of this pull request

This pull request (PR) extends Import/Export documentation with remote storage functionality.

## Magento release version

- [ ] 2.4.2

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source
- [ ] Magento Commerce

## Affected documentation pages:
- src/system/data-export.md
- src/system/data-import.md
- src/system/data-import-history.md
- src/system/data-import-product-images.md
- src/system/data-schedule-export.md
- src/system/data-schedule-import.md
- src/system/data-transfer-downloadable-products.md
- src/system/data-transfer-examples.md

## Additional information

Here is a PR with this functionality to 2.4-develop that is going to be merged: https://github.com/magento-commerce/magento2ce/pull/6344

2020-11-16 20:06 UTC, leslietilling commented on src/system/data-import-product-images.md
> +    e.g. product_images
```suggestion
var/import/images/product_images
```

2020-11-16 21:45 UTC, leslietilling requested changes
Some minor edits and linting fixes

2020-11-18 21:10 UTC, hguthrie requested changes
I cleaned up a few things.
I think that there is a lot of repetition about remote storage enablement, but it looks like there is a good reason. @leslietilling should there be a link to devdocs about enabling Remote storage? Or should there be a section somewhere in Merchant docs about Enabling remote storage...?

2020-11-18 21:21 UTC, leslietilling commented on src/system/data-export.md
> +    By default, all exported files are located in the `<Magento root directory>/var/export` folder. If remote storage like Amazon S3 is enabled, all exported files are located in the `<Remote storage
@hguthrie  We should link to devdocs for enabling remote storage. I don't know of anything to do that via the Admin.

2020-11-18 21:22 UTC, leslietilling commented
> I cleaned up a few things.
> I think that there is a lot of repetition about remote storage enablement, but it looks like there is a good reason. @leslietilling should there be a link to devdocs about enabling Remote storage? Or should there be a section somewhere in Merchant docs about Enabling remote storage...?

@hguthrie We should link to devdocs for enabling remote storage. I don't know of anything to do that via the Admin.

2020-12-01 22:38 UTC, hguthrie commented
Sorry for the delay. Holidays and much more going on. I will wrap up this edit now that the Config Guide updates are in final editorial review. The config guide Remote storage section refers to the Schedule Imports/Exports topic in the User guide. I will see where it might help to link back to config...

2020-12-02 19:45 UTC, hguthrie approved these changes
I finished reviewing. I do think that the repeated note is a candidate for include file, so I would like to merge this into a new branch to make that structural change before creating a new PR to 2.4.2-develop for release.

2020-12-02 19:49 UTC, merged