PB-636: Responsive breakpoint switcher
magento/merchdocs pull request #938
Opened 2020-12-12 19:44 UTC by bdenham

## Purpose of this pull request

This pull request (PR) adds a Page Builder topic for a new feature for 2.4.2: Admin viewport switchers.

## Story

[PB-636: Responsive breakpoint switcher](https://github.com/magento/magento2-page-builder/issues/636)

## Magento release version

- [x] 2.4.2

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [x] Other feature set, please specify: Page Builder

whatsnew
Page Builder adds a viewport switcher to the admin stage so users can preview how their content will look on different devices (desktop vs. mobile).

2020-12-14 19:15 UTC, leslietilling requested changes
Some editorial updates for consistency in user guide.

2020-12-14 19:15 UTC, leslietilling commented on src/cms/page-builder-workspace.md
> +A viewport is the visible area of a web page that a user sees. On the stage, when it is in full-screen design mode, Page Builder displays viewport buttons above the stage to show you the content as t
```suggestion
A _viewport_ is the visible area of a web page that a user sees. When it is in full-screen design mode, Page Builder displays viewport buttons above the stage to show you the content as the site user will see it on the storefront.
```

2020-12-14 19:15 UTC, leslietilling commented on src/cms/page-builder-workspace.md
> +Page Builder also defines breakpoints to its viewports. Breakpoints define minimum and maximum widths within which certain styles are applied. Page Builder's two viewports define the following breakp
```suggestion
Page Builder also defines breakpoints for viewports. Breakpoints define minimum and maximum widths within which certain styles are applied. The Page Builder viewports provide the following content breakpoints:
```

2020-12-14 19:15 UTC, leslietilling commented on src/cms/page-builder-workspace.md
> +### Content previews
Empty line after heading

```suggestion
### Content previews

```

2020-12-14 19:15 UTC, leslietilling commented on src/cms/page-builder-workspace.md
> +- **Desktop** — Previews your content without a predefined width. Desktop-defined styles (using breakpoint minimum width of 1024px) are still applied to the page. But the Desktop viewport width is de
```suggestion
- **Desktop** — Displays the content preview without a predefined width. Desktop-defined styles (using breakpoint minimum width of 1024px) are still applied to the page. But the Desktop viewport width is defined by settings for container content types, like Rows. Selecting the Desktop viewport shows how your content will be styled on the storefront when the browser page width is 1024px and wider.
```

2020-12-14 19:15 UTC, leslietilling commented on src/cms/page-builder-workspace.md
> +- **Mobile** — Previews your content at a predefined width of 768px. Unlike the Desktop viewport, the Mobile viewport does show your page content at a width of 768px, along with the styles defined fo
```suggestion
- **Mobile** — Displays the content preview at a predefined width of 768px. Unlike the Desktop viewport, the Mobile viewport does show your page content at a width of 768px, along with the styles defined for the breakpoint widths of 768px (max) and 640px (min).
```

2020-12-14 19:15 UTC, leslietilling commented on src/cms/page-builder-workspace.md
> +The following screenshots show Page Builder's default responsive settings for product carousels displayed for these viewports:
```suggestion
The following examples show the Page Builder default responsive settings for product carousels displayed for these viewports:
```

2020-12-14 19:15 UTC, leslietilling commented on src/cms/page-builder-workspace.md
> +### Breakpoint settings
Empty line after heading

```suggestion
### Breakpoint settings

```

2020-12-14 19:15 UTC, leslietilling commented on src/cms/page-builder-workspace.md
> +The viewport buttons also provide the option to apply different breakpoint styles to content types based on the selected viewport. By default, Page Builder provides breakpoint settings for the Minimu
```suggestion
The viewport buttons also provide the option to apply different breakpoint styles to content types based on the selected viewport. By default, Page Builder provides breakpoint settings for the _Minimum Height_ settings of Rows, Columns, Tabs, Tab Items, Banners, Sliders, and Slides. When you select the Mobile viewport and then open the editor for one of those content types, you can enter values specific to the Mobile viewport. Content type fields that allow specific breakpoint settings display an icon to the right of the field, similar to the following example for a Row:
```

2020-12-14 23:45 UTC, bdenham commented on src/cms/page-builder-workspace.md
> +A viewport is the visible area of a web page that a user sees. On Page Builder's stage, when it is in Page Builder's full-screen design mode, Page Builder displays viewport buttons above the stage to
Yes, viewport is a standard term.

2020-12-15 00:01 UTC, omiroshnichenko approved these changes

2020-12-15 14:40 UTC, leslietilling approved these changes

2020-12-15 14:46 UTC, leslietilling commented
Please squash when merging and add `whatsnew`

2020-12-15 15:08 UTC, bdenham commented
running tests

2020-12-15 15:26 UTC, bdenham commented
running tests

2020-12-15 15:32 UTC, merged