update manage subscribers page v2.3.x
magento/merchdocs pull request #951
Opened 2020-12-17 06:48 UTC by chiranjeevi-cj

## Purpose of this pull request

This pull request (PR) updates the manage subscriber page.

## Magento release version

- [ ] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/v2.3/marketing/newsletter-subscribers.html

## Additional information

Fixes #571

2020-12-21 17:59 UTC, leslietilling requested changes
Edit for note within a procedure step.

2020-12-21 17:59 UTC, leslietilling commented on src/marketing/newsletter-subscribers.md
> +1. Find the subscriber in the grid and select the checkbox in the first column. **Note** For the bulk unsubscribe select the checkbox of each subscriber that you want to cancel.
```suggestion
1. Find the subscriber in the grid and select the checkbox in the first column.

   {:.bs-callout-info}
   For a bulk unsubscribe, select the checkbox of each subscriber that you want to cancel.
```

2020-12-21 18:04 UTC, leslietilling approved these changes

2020-12-21 18:20 UTC, leslietilling commented
running tests

2020-12-21 20:02 UTC, leslietilling commented
@dshevtsov  One of the checks is "stuck" -- do we need an update on the `2.3-production` branch to omit this test?

2021-01-04 15:34 UTC, dshevtsov commented
@leslietilling, we need an update on the branch to enable this check.
I'll create a PR.

2021-01-04 17:39 UTC, dshevtsov commented
#963

2021-01-04 17:46 UTC, dshevtsov commented
running tests

2021-01-04 17:57 UTC, leslietilling commented
@dshevtsov  Thanks for fixing for this branch :)

2021-01-04 17:57 UTC, merged