B2B Add payment limitation info around purchase orders
magento/merchdocs pull request #976
Opened 2021-01-11 17:37 UTC by dobooth

## Purpose of this pull request

This pull request (PR) adds information about limitations around payments when processing purchase orders.

## Magento release version

- 2.4.2

## Product editions

- B2B extension

## Affected documentation pages

https://docs.magento.com/user-guide/customers/account-dashboard-my-purchase-orders.html

2021-01-11 23:09 UTC, leslietilling requested changes
I would make the context information a general note and leave the other as a warning. In this case I think we can put one after the other.

2021-01-11 23:09 UTC, leslietilling commented on src/customers/account-dashboard-approval-rules.md
> +{:.bs-callout-warning}
```suggestion
{:.bs-callout-info}
```

2021-01-11 23:09 UTC, leslietilling commented on src/customers/account-dashboard-approval-rules.md
> +Also, using gift cards, store credit, or reward points with online payment methods for purchase orders is not supported. Enabling these features with online payments may cause some unexpected behavio
```suggestion

{:.bs-callout-warning}
Using gift cards, store credit, or reward points with online payment methods for purchase orders is not supported. Enabling these features with online payments may cause some unexpected behavior. It is recommended to disable gift cards, store credit, and reward points when online payments are enabled for purchase orders.
```

2021-01-11 23:09 UTC, leslietilling commented on src/customers/account-dashboard-approval-rules.md
> +## Purchase order payment methods
Need a blank before the heading

```suggestion

## Purchase order payment methods
```

2021-01-12 13:55 UTC, dobooth commented
I suspected I was overloading that warning...

2021-01-12 14:55 UTC, leslietilling approved these changes
Just that minor fix and good to go!  Let's make sure to squash :)

2021-01-12 14:55 UTC, leslietilling commented on src/customers/account-dashboard-approval-rules.md
> +Generally, _In-Context_ means the customer stays on the Magento site to complete the process. _Out-of-Context" is when the customer is taken to another site to complete the purchase.
My boo boo from last round

```suggestion
Generally, _In-Context_ means the customer stays on the Magento site to complete the process. _Out-of-Context_ is when the customer is taken to another site to complete the purchase.
```

2021-01-12 16:16 UTC, dobooth commented
running tests

2021-01-12 16:56 UTC, merged

2021-02-02 19:20 UTC, leslietilling commented
@dobooth  Let's add a "Whats New" for this one.