Update price-rule-catalog-scheduled-changes.md
magento/merchdocs pull request #999
Opened 2021-01-21 14:45 UTC by serhii-balko

The documentation updated according to the https://jira.corp.magento.com/browse/MC-40490

## Purpose of this pull request

This pull request (PR) ...

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable: 2.4.3

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/marketing/price-rule-catalog-scheduled-changes.html

## Links to Magento source code or PRs

- ...
- ...

## Additional information

https://jira.corp.magento.com/browse/MC-40490

2021-01-21 15:42 UTC, chernenm requested changes
Hi @serhii-balko, we may use the following a bit rephrased statement:

"Please note, that date and time is set in the default Admin panel time zone, but not in a particular website time zone. If you have a different Time Zone on your website you should take in to account a time offset between them."

2021-01-26 15:54 UTC, dobooth approved these changes

2021-01-26 15:54 UTC, dobooth approved these changes

2021-01-27 16:07 UTC, chernenm approved these changes

2021-01-27 16:53 UTC, dobooth commented
running tests

2021-01-27 16:59 UTC, merged